jaredwray/cacheable

README.md
src/index.js
test/cacheable-request-instance.js

Resolves https://github.com/lukechilds/cacheable-request/issues/14

Error handling

---

src/index.js
test/cache.js

relates to:
- #43 
- https://github.com/sindresorhus/got/pull/519

fix: ensure query parsed from path option is passed along

---

README.md
package.json
src/index.js
test/cache.js
test/cacheable-request-instance.js

Fixes https://github.com/sindresorhus/got/issues/597

Introduce `opts.forceRefresh`, compare status codes when retrieving from cache

---

package.json

fix(package): update normalize-url to version 4.1.0

---

package.json

Update nyc to version 14.1.1

---

package.json

Update get-stream to version 5.1.0

---

package.json

fix #103 
CVE-2021-33502: https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-33502

build(deps): upgrade `normalize-url` to fix vulnerability

---

package.json
src/index.js
test/cache.js
test/cacheable-request-class.js
test/cacheable-request-instance.js

Update `cacheable-request` for esm compatibility

Convert package to esm

---

src/index.ts
test/cache.test.ts

fixed for 304

---

package.json
src/index.ts

Doing a conversion on headers to Record<string, string> for new module.

upgrading responseLink to 3.0.0

---

test/cache.test.ts

removing console.log from tests

removing console.log from tests

---

package.json

upgrading @types/node to 18.7.3

upgrading @types/node to 18.7.3

---

SECURITY.md

updating security readme on support for v8.x.x

---

package.json

upgrading keyv to 4.4.1

---

README.md
package.json
src/index.ts
src/types.ts
test/cache.test.ts
test/cacheable-request-class.test.ts
test/cacheable-request-instance.test.ts

fixed hooks instance issue

---

package.json

upgrading jest and ts-jest to version 29

upgrading jest and ts-jest to version 29

---

package.json

upgrading @types/node to 18.7.16

upgrading @types/node to 18.7.16

---

package.json

upgrading eslint-plugin-jest to 27.0.4

upgrading eslint-plugin-jest to 27.0.4

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md
README.md
SECURITY.md

updating documentation to on contribution

updating documentation to on contribution

---

.github/PULL_REQUEST_TEMPLATE.md
README.md

[ ] Followed the guidelines in the [Contributing](CONTRIBUTING.md) document.
[ ] Tests for the changes have been added (for bug fixes/features) with 100% code coverage.
[ ] Docs have been added / updated (for bug fixes / features)
adding in table of contents

adding in table of contents

---

.github/PULL_REQUEST_TEMPLATE.md
package.json

upgrading keyv to 4.5.0

---

SECURITY.md

adding a warning to security document on v8 support

adding a warning to security document on v8 support

---

package.json

upgrading typescript to 4.8.3

---

package.json

upgrading normalize-url to 7.1.0

upgrading normalize-url to 7.1.0

---

README.md
src/index.ts
src/types.ts
test/cache.test.ts
test/cacheable-request-class.test.ts

added remote address

---

package.json

upgrading xo to 0.52.4

---

package.json

upgrading typescript to 4.8.4

---

package.json

upgrading sqlite3 to 5.1.2

---

package.json

upgrading jest to 29.2.1

---

package.json

upgrading ts-jest to 29.0.3

---

package.json

upgrading eslint-plugin-jest to 27.1.3

upgrading eslint-plugin-jest to 27.1.3

---

package.json

upgrading normalize-url to 7.2.0

upgrading normalize-url to 7.2.0

---

package.json

upgrading @keyv/sqlite to 3.6.2

upgrading @keyv/sqlite to 3.6.2

---

package.json

upgrading typescript to 4.9.3

---

package.json

upgrading keyv to 4.5.2

---

package.json

upgrading normalize-url to 8.0.0

upgrading normalize-url to 8.0.0

---

package.json

upgrading sqlite3 to 5.1.4

---

src/index.ts

fixing listener memory leak - issue #222

fixing listener memory leak - issue #222

---

package.json

security fix for http-cache-semantics 4.1.1

security fix for http-cache-semantics 4.1.1

---

package.json

upgrading body-parser to 1.20.2

upgrading body-parser to 1.20.2

---

package.json

upgrading @types/node to 18.15.10

upgrading @types/node to 18.15.10

---

package.json

**What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...
upgrading sqlite3 and @keyv/sqlite to latest

upgrading sqlite3 and @keyv/sqlite to latest

---

package.json
src/index.ts
test/cache.test.ts

Upgrading xo to 0.54.1

---

package.json

upgrading typescript and ts-jest to latest

upgrading typescript and ts-jest to latest

---

package.json

upgrading xo to 0.54.2

---

package.json
src/index.ts
test/cache.test.ts

fixing eslint error and validation

---

package.json

upgrading keyv and components to latest

upgrading keyv and components to latest

---

package.json

upgrading babel to latest versions

upgrading babel to latest versions

---

package.json

upgrading http-cache-semantics to 4.1.1

upgrading http-cache-semantics to 4.1.1

---

.github/workflows/tests.yaml
package.json
src/index.ts

Also, moved to using `getStreamAsBuffer ` as the function

upgraded get-stream to 7.0.0

---

packages/request/package.json
packages/request/tsconfig.json

fixing source map issues by including src directory

fixing source map issues by including src directory

---

.gitignore
packages/request/package.json

upgrading xo to 0.55.0

---

packages/request/package.json

removing @types/delay and @types/get-stream as it is included

removing @types/delay and @types/get-stream as it is included

---

packages/website/site/_data/github.json
packages/website/site/_includes/shared/head.njk

adding in the cacheable icon for browsers

adding in the cacheable icon for browsers

---

packages/request/README.md

request - updating readme with simple logo

request - updating readme with simple logo

---

packages/cacheable/README.md
packages/website/package.json
packages/website/src/docs.ts

updating website

---

README.md

mono - updating README with packages description

mono - updating README with packages description

---

packages/cacheable/package.json
packages/cacheable/src/index.ts

cacheable - adding in features and testing

cacheable - adding in features and testing

---

packages/request/package.json

request - upgrading xo to 0.56.0

request - upgrading xo to 0.56.0

---

packages/request/package.json

request - upgrading eslint and typescript to latest

request - upgrading eslint and typescript to latest

---

packages/request/package.json

request - upgrading jest to 29.6.4

request - upgrading jest to 29.6.4

---

packages/request/package.json

request - upgrading @keyv/sqlite to 3.6.5

request - upgrading @keyv/sqlite to 3.6.5

---

packages/request/package.json

request - upgrading types to latest

request - upgrading types to latest

---

packages/request/LICENSE

adding a license file to cacheable-request

adding a license file to cacheable-request

---

packages/request/package.json

request - upgrading keyv to 4.5.4

request - upgrading keyv to 4.5.4

---

packages/request/package.json

request - upgrading types to latest versions

request - upgrading types to latest versions

---

packages/cacheable/package.json
packages/request/package.json

request - upgrading modules to latest such as eslint and types

request - upgrading modules to latest such as eslint and types

---

packages/request/package.json
packages/request/test/cacheable-request-instance.test.ts

request - upgrading sqlite3 to 5.1.7

request - upgrading sqlite3 to 5.1.7

---

.github/workflows/tests.yaml
packages/request/package.json
packages/request/src/index.ts
packages/request/test/cache.test.ts

request - upgrading get-stream to 8.0.1
Fixing https://github.com/jaredwray/cacheable/issues/272 and https://github.com/jaredwray/cacheable/issues/251

request - upgrading get-stream to 8.0.1

---

.github/workflows/tests.yaml
packages/request/package.json
packages/request/src/index.ts
packages/request/src/types.ts
packages/request/test/cache.test.ts

request - upgrading xo and eslint to latest

request - upgrading xo and eslint to latest

---

packages/request/package.json

request - @keyv/sqlite to 3.6.7

request - @keyv/sqlite to 3.6.7

---

packages/request/package.json

upgrading xo to 0.58.0

---

packages/request/package.json

upgrading typescript to 5.4.3

---

packages/request/package.json

upgrading normalize-url to 8.0.1

upgrading normalize-url to 8.0.1

---

packages/request/package.json

upgrading get-stream to 9.0.1

---

.github/workflows/tests.yaml
packages/cacheable-request/package.json

cacheable-request - upgrading typescript to 5.4.5

cacheable-request - upgrading typescript to 5.4.5

---

packages/cacheable-request/package.json

cacheable-request - upgrading vitest to 1.6.0

cacheable-request - upgrading vitest to 1.6.0

---

packages/cacheable-request/package.json

cacheable-request - upgrading types and typescript to lastes

cacheable-request - upgrading types and typescript to lastes

---

packages/cacheable-request/src/index.ts
packages/cacheable-request/test/create-test-server/index.mjs

cacheable-request - adding in ignores on throwing errors

cacheable-request - adding in ignores on throwing errors

---

.github/workflows/tests.yaml

updating tests to 18 and 20 nodejs

updating tests to 18 and 20 nodejs
