jaredwray/cacheable

- lib/multi_caching.js
- test/multi_caching.unit.js
If higher level caches don't have a key, they will be given it if it exists in a lower level.
> Get and pass up feature to update higher caches

- lib/stores/memory.js
> memoryStore 增加set方法的ttl

- .jshintrc
- lib/caching.js
- lib/multi_caching.js
- lib/stores/memory.js
- test/caching.unit.js
- test/multi_caching.unit.js
- test/run.js
> Allow passing in a promise dependency

- README.md
Better performance for binary data caches than in node-cache-manager-fs
> add node-cache-manager-fs-binary storage

- README.md
Add node-cache-manager-memcached-store link to readme
See https://github.com/theogravity/node-cache-manager-memcached-store
> Add node-cache-manager-memcached-store ref

- lib/multi_caching.js
- test/multi_caching.unit.js
Hi @BryanDonovan 
recently i needed to reset a cache independent of wether it's multi_cache or a particular store, and i was surprised to see the multi_cache doesn't implement it. Hence the pull request. Bless please
> add multi_caching.reset()

- README.md
Sorry couldn't resist, the blurriness offended me.
> Use svg badges in readme

- README.md
> Fix syntax error in readme example

- lib/stores/memory.js
Add null as first argument for callback if no error.
> null as first argument to keep style consistent

- lib/caching.js
> Add explicit return in wrapPromise.

- lib/callback_filler.js
- lib/multi_caching.js
- test/multi_caching.unit.js
Closes #105 
If you isolate the new unit test and run it against current `master`, you'll see the test fail via timeout.
> fix multicaching when result is not cacheable

- lib/multi_caching.js
We have a problem using multi-caching with cache-manager-memcached-store.
https://github.com/arash16/nuxt-ssr-cache/issues/7
> bind isCacheableValue to it's underlying store

- README.md
- lib/stores/none.js
- test/stores/none.unit.js
Store can be used for development functionality, when we want to
disable real cache, but still want to have callbacks\promises working.
It can fix the issue when we want to disable\enable the cache:
https://github.com/BryanDonovan/node-cache-manager/issues/92
> Development store "none"

- README.md
Hi there! I've created a provider for Couchbase Server and added the reference to your README. Hope you don't mind!
> Added node-cache-manager-couchbase reference

- README.md
This is a PR to address #199 
Ping @BryanDonovan so you get notified, sorry for the annoyance 😄
> chore: new node-cache-manager-ioredis repo in README

- test/caching.test.ts
> chore(coverage): add coverage for issue #183

- examples/nestv9/.eslintrc.js
- examples/nestv9/.gitignore
- examples/nestv9/.prettierrc
- examples/nestv9/README.md
- examples/nestv9/nest-cli.json
- examples/nestv9/package.json
- examples/nestv9/pnpm-lock.yaml
- examples/nestv9/src/app.controller.ts
- examples/nestv9/src/app.module.ts
- examples/nestv9/src/cache/cache.module-definition.ts
- examples/nestv9/src/cache/cache.module.ts
- examples/nestv9/src/cache/cache.provider.ts
- examples/nestv9/src/cache/index.ts
- examples/nestv9/src/main.ts
- examples/nestv9/tsconfig.build.json
- examples/nestv9/tsconfig.json
- src/caching.ts
> chore: add example module for nestjs v9

- README.md
- READMEv4.md
> fix: links to ioredis in Readme

- src/caching.ts
- src/multi-caching.ts
- test/caching.test.ts
- test/multi-caching.test.ts
#532
Allows to set the `ttl` of the `wrap` function based on the return of fn.
> feat: the ttl of wrap could be function

- package.json
> upgrading vitest to 0.34.4

- package.json
upgrading @vitest/coverage-v8 to 0.34.4
> upgrading @vitest/coverage-v8 to 0.34.4

- package.json
> upgrading vitest to 0.34.6

- package.json
> upgrading lru-cache to 10.0.1

- package.json
upgrading @faker-js/faker to 8.1.0
> upgrading @faker-js/faker to 8.1.0

- package.json
> upgrading lru-cache to 10.0.2

- package.json
- vite.config.ts
> updating vitest to 1.1.0

- package.json
upgrading promise-coalesce to 1.1.2
> upgrading promise-coalesce to 1.1.2

- package.json
> upgrading lru-cache to 10.1.0

- package.json
> upgrading vitest to 1.2.1

- test/caching.test.ts
- test/multi-caching.test.ts
fixing multi-cache testing of ttl wrap function
> fixing multi-cache testing of ttl wrap function

- README.md
> Adding SQLite storage(use better-sqlite3)

- .gitignore
- CONTRIBUTING.md
updating contributing guidelines
> updating contributing guidelines

- README.md
updating readme to correct paths
> updating readme to correct paths

- package.json
removing dotenv-cli as it is not used
> removing dotenv-cli as it is not used

- README.md
- package.json
- src/caching.ts
updating documentation and version
> updating documentation and version

- README.md
- packages/cache-manager-ioredis-yet/README.md
- packages/cache-manager-redis-yet/README.md
- packages/cache-manager/README.md
> updating readme with new path

- docker-compose.yml
- packages/cache-manager-ioredis-yet/test/index.test.ts
- packages/cache-manager-redis-yet/test/index.test.ts
adding in two redis servers for testing
> adding in two redis servers for testing

- packages/cache-manager-redis-yet/package.json
redis - upgrading vitest to 1.4.0
> redis - upgrading vitest to 1.4.0

- packages/cache-manager-redis-yet/package.json
redis - updating cache-manager to 5.5.1
> redis - updating cache-manager to 5.5.1

- packages/cache-manager-redis-yet/package.json
- packages/cache-manager-redis-yet/test/index.test.ts
redis - upgrading typescript to 5.4.4
> redis - upgrading typescript to 5.4.4

- packages/cache-manager/package.json
fixing the xo runner on test:ci
> fixing the xo runner on test:ci

- packages/cache-manager-ioredis-yet/package.json
- packages/cache-manager-redis-yet/package.json
- packages/cache-manager/package.json
cache-manager - upgrading typescript and types to latest
> cache-manager - upgrading typescript and types to latest

- packages/cache-manager/package.json
> upgrading lru-cache to 10.2.2

- packages/cache-manager/package.json
cache-manager - upgrading vitest to 1.5.2
> cache-manager - upgrading vitest to 1.5.2

- packages/cache-manager-ioredis-yet/package.json
cache-manager-ioredis-yet - upgrading typescript to 5.4.5
> ioredis-yet - upgrading typescript to 5.4.5

- packages/cache-manager-ioredis-yet/package.json
ioredis-yet - upgrading eslint to 9.1.1
> ioredis-yet - upgrading eslint to 9.1.1

- packages/cache-manager-ioredis-yet/package.json
ioredis-yet - upgrading ioredis to 5.4.1
> ioredis-yet - upgrading ioredis to 5.4.1

- packages/cache-manager-ioredis-yet/package.json
ioredis-yet - upgrading vitest to 1.5.2
> ioredis-yet - upgrading vitest to 1.5.2

- packages/cache-manager-redis-yet/package.json
redis-yet - upgrading typescript to 5.4.5
> redis-yet - upgrading typescript to 5.4.5

- packages/cache-manager/README.md
documentation fix for memory store on createCache fixing issue #687
> documentation fix for memory store on createCache

- docker-compose.yml
fixing docker-compose issue with version
> fixing docker-compose issue with version

- packages/cache-manager/package.json
cache-manager - upgrading vitest to 1.6.0
> cache-manager - upgrading vitest to 1.6.0

- packages/cache-manager-ioredis-yet/package.json
ioredis - upgrading rimraf to 5.0.7
> ioredis - upgrading rimraf to 5.0.7

- packages/cache-manager-redis-yet/package.json
redis - upgrading vitest to 1.6.0
> redis - upgrading vitest to 1.6.0

- packages/cache-manager-redis-yet/package.json
redis - upgrading redis to 4.6.14
> redis - upgrading redis to 4.6.14

- packages/cache-manager-redis-yet/package.json
redis - upgrading eslint to latest
> redis - upgrading eslint to latest

- packages/cache-manager-ioredis-yet/package.json
- packages/cache-manager-ioredis-yet/tsconfig.json
- packages/cache-manager-redis-yet/package.json
- packages/cache-manager-redis-yet/tsconfig.json
- packages/cache-manager/package.json
- packages/cache-manager/tsconfig.json
moving to typescript compatibility with nodejs 18+
> moving to typescript compatibility with nodejs 18+

- packages/cache-manager/README.md
adding in express middleware example
> adding in express middleware example

- .github/PULL_REQUEST_TEMPLATE.md
- packages/cache-manager-ioredis-yet/package.json
- packages/cache-manager-ioredis-yet/tsconfig.json
- packages/cache-manager-redis-yet/package.json
- packages/cache-manager-redis-yet/tsconfig.json
- packages/cache-manager/package.json
- packages/cache-manager/tsconfig.json
> updating tsconfig to commonjs

- README.md
- packages/cache-manager/package.json
mono - updating modules to latest in root
> mono - updating modules to latest in root

- packages/cache-manager-ioredis-yet/package.json
ioredis - upgrading typescript and eslint to latest
> ioredis - upgrading typescript and eslint to latest

- packages/cache-manager-redis-yet/package.json
redis - upgrading eslint and typescript to latest
> redis - upgrading eslint and typescript to latest

- packages/cache-manager-redis-yet/src/index.ts
- packages/cache-manager-redis-yet/test/index.test.ts
fix: cache prefix on del and mdel for #709
> fix: cache prefix on del and mdel

- package.json
> mono - upgrading c8 to 10.1.2

- packages/cache-manager/package.json
cache-manager - upgrading typescript and modules to latest
> cache-manager - upgrading typescript and modules to latest

- packages/cache-manager/package.json
- packages/cache-manager/vite.config.ts
cache-manager - upgrading vitest to 2.0.2
> cache-manager - upgrading vitest to 2.0.2

- packages/cache-manager/package.json
cache-manager - upgrading rimraf to 6.0.1
> cache-manager - upgrading rimraf to 6.0.1

- packages/cache-manager/package.json
cache-manager - upgrading lrucache to 11.0.0
> cache-manager - upgrading lrucache to 11.0.0

- packages/cache-manager-ioredis-yet/package.json
ioredis - upgrading typescript and modules to latest
> ioredis - upgrading typescript and modules to latest

- packages/cache-manager-ioredis-yet/package.json
ioredis - upgrading vitest to 2.0.2
> ioredis - upgrading vitest to 2.0.2

- packages/cache-manager-redis-yet/package.json
redis - upgrading typescript and eslint modules to latest
> redis - upgrading typescript and eslint modules to latest

- packages/cache-manager-redis-yet/package.json
redis - upgrading vitest to 2.0.2
> redis - upgrading vitest to 2.0.2

- packages/cache-manager-redis-yet/package.json
redis - upgrading redis to 4.6.15 and @redis/client to latest
> redis - upgrading redis to 4.6.15 and @redis/client to latest

- packages/cache-manager-redis-yet/package.json
- packages/cache-manager/LICENSE
- packages/cache-manager/package.json
redis - updating to include license file
> redis - updating to include license file

- README.md
**What kind of change does this PR introduce?**
Docs update
> Update README.md to add cache-manager-bun-sqlite3

- packages/cache-manager/package.json
cache-manager - upgrading vitest to 2.0.4
> cache-manager - upgrading vitest to 2.0.4

- packages/cache-manager-ioredis-yet/package.json
ioredis - upgrading vitest to 2.0.4
> ioredis - upgrading vitest to 2.0.4

- packages/cache-manager-redis-yet/package.json
redis - upgrading eslint and vitest to latest
> redis - upgrading eslint and vitest to latest

- packages/cache-manager/package.json
cache-manager - upgrading xo and @types/node to latest
> cache-manager - upgrading xo and @types/node to latest

- packages/cache-manager/README.md
- packages/cache-manager/package.json
> updating readme

- README.md
- packages/website/site/docs/index.md
updating how to contribute instructions
> updating how to contribute instructions

- packages/cache-manager/package.json
cache-manager - upgrading vitest to 2.0.5
> cache-manager - upgrading vitest to 2.0.5

- README.md
- packages/cache-manager-ioredis-yet/README.md
- packages/cacheable-request/README.md
codecov - fixing codecov badge across projects
> codecov - fixing codecov badge across projects

- .github/workflows/deploy-website.yml
- packages/cache-manager-redis-yet/package.json
- packages/cache-manager-redis-yet/src/index.ts
- packages/website/package.json
cache-manager-redis: updating console error on connection failure #750
> cache-manager-redis: updating console error on connection failure

- packages/cache-manager-redis-yet/package.json
cache-manager-redis: upgrading redis to 4.7.0
> cache-manager-redis: upgrading redis to 4.7.0

- packages/cache-manager-redis-yet/package.json
cache-manager-redis: upgrading eslint and modules to latest
> cache-manager-redis: upgrading eslint and modules to latest

- packages/cache-manager-redis-yet/package.json
cache-manager-redis: upgrading cache-manager to 5.7.6
> cache-manager-redis: upgrading cache-manager to 5.7.6

- packages/cache-manager-redis-yet/package.json
cache-manager-redis: upgrading redis modules to latest
> cache-manager-redis: upgrading redis modules to latest

- packages/website/src/docs.ts
**What kind of change does this PR introduce?**
Fix Typo in docs
> Fix typo in website

- .github/workflows/tests.yml
- packages/cacheable/README.md
- packages/cacheable/package.json
- packages/cacheable/src/index.ts
> init release to npm

- packages/cacheable/README.md
- packages/cacheable/package.json
> cacheable - adding in rimraf

- README.md
- packages/cache-manager/README.md
- packages/cacheable-request/README.md
- packages/cacheable/README.md
- packages/cacheable/package.json
- packages/cacheable/src/index.ts
- packages/website/package.json
- packages/website/src/docs.ts
> updating readme and website

- packages/cacheable/README.md
- packages/cacheable/src/index.ts
> adding in cache mode

- packages/node-cache/README.md
- packages/node-cache/package.json
- packages/node-cache/src/index.ts
- packages/node-cache/test/index.test.ts
- packages/node-cache/tsconfig.build.json
- packages/node-cache/tsconfig.json
Adding in Node Cache to have it be more maintained and in typescript
> Building out Node Cache

- packages/cacheable/README.md
- packages/cacheable/package.json
- packages/cacheable/src/index.ts
- packages/cacheable/test/index.test.ts
- packages/cacheable/vite.config.ts
cacheable - adding in unit tests and default functionality
> cacheable - adding in unit tests and default functionality

- packages/cacheable/README.md
- packages/cacheable/package.json
- packages/cacheable/src/index.ts
- packages/cacheable/src/stats.ts
- packages/cacheable/test/index.test.ts
- packages/cacheable/test/stats.test.ts
- packages/cacheable/tsconfig.json
adding in stats, getMany, setMany, primary, and secondary layers
> cacheable - adding in stats, getMany, setMany, primary, and secondary layers

- packages/node-cache/package.json
- packages/node-cache/tsconfig.json
node-cache - moving to esm and cjs with vitest updated
> node-cache - moving to esm and cjs with vitest updated

- packages/website/package.json
- packages/website/src/docs.cts
> website - running as cjs

- packages/cacheable/README.md
- packages/cacheable/src/index.ts
> exporting CacheableStats

- packages/cacheable/README.md
- packages/cacheable/src/index.ts
- packages/cacheable/src/stats.ts
- packages/cacheable/test/index.test.ts
- packages/cacheable/test/stats.test.ts
this implements the stats in the system
> Implementing stats

- packages/cacheable/README.md
- packages/cacheable/src/index.ts
- packages/cacheable/src/memory-lru.ts
- packages/cacheable/src/memory.ts
- packages/cacheable/test/memory.test.ts
CacheableInMemory - Creating an In Memory Storage that is better that Map which is the current default with Keyv. Features include:
> CacheableInMemory - Creating an In Memory Storage

- packages/cacheable/package.json
upgrading typescript and dev dependencies
> upgrading typescript and dev dependencies

- packages/node-cache/package.json
- packages/node-cache/src/index.ts
node-cache - updating clone via CacheableMemory
> node-cache - updating clone via CacheableMemory

- packages/node-cache/src/index.ts
- packages/node-cache/tsconfig.build.json
> adding in stats

- packages/node-cache/package.json
- packages/node-cache/src/store.ts
- packages/node-cache/test/store.test.ts
node-cache - adding in NodeCacheStore
> node-cache - adding in NodeCacheStore

- packages/cacheable/src/index.ts
- packages/cacheable/test/index.test.ts
> cacheable - adding in ttl

- packages/node-cache/README.md
- packages/node-cache/package.json
- packages/node-cache/src/index.ts
- packages/node-cache/src/store.ts
- packages/node-cache/test/index.test.ts
- packages/node-cache/test/store.test.ts
> node-cache - NodeCacheStore

- packages/node-cache/README.md
- packages/node-cache/package.json
- packages/node-cache/src/store.ts
- packages/node-cache/test/store.test.ts
node-cache - adding in support take() and disconnect()
> node-cache - adding in support take() and disconnect()

- packages/cacheable/package.json
- packages/cacheable/src/index.ts
- packages/cacheable/test/index.test.ts
CJS and ESM Support with updated Hookified library
> Cacheable   updating hookified and keyv to latest

- packages/cacheable/README.md
cacheable - updating documentation on many functionality
> cacheable - updating documentation on many functionality

- packages/cacheable/README.md
- packages/cacheable/package.json
- packages/cacheable/src/memory.ts
- packages/cacheable/test/memory.test.ts
Adding in `checkInterval` which will check for expiration at a timed interval if set to greater that 0 milliseconds.
> Cacheable   adding in interval check for cacheable memory

- packages/cache-manager/README.md
- packages/cache-manager/package.json
- packages/cache-manager/src/index.ts
- packages/cache-manager/test/clear.test.ts
- packages/cache-manager/test/del.test.ts
- packages/cache-manager/test/get.test.ts
- packages/cache-manager/test/mdel.test.ts
- packages/cache-manager/test/set.test.ts
Cache manager -  adding in non blocking
> Cache manager -  adding in non blocking

- packages/cacheable/README.md
cacheable - updating readme with coming soon on cache sync
> cacheable - updating readme with coming soon on cache sync

- packages/cacheable/src/index.ts
- packages/cacheable/src/keyv-memory.ts
- packages/cacheable/test/keyv-memory.test.ts
cacheable - adding KeyvCacheableMemory Adapter
> cacheable - adding KeyvCacheableMemory Adapter

- packages/node-cache/README.md
- packages/node-cache/src/store.ts
node-cache - updating the readme on ttl for NodeCacheStore
> node-cache - updating the readme on ttl for NodeCacheStore

- packages/node-cache/package.json
node-cache - upgrading cacheable to 1.6.0
> node-cache - upgrading cacheable to 1.6.0

- packages/flat-cache/LICENSE
- packages/flat-cache/README.md
- packages/flat-cache/package.json
- packages/flat-cache/src/index.ts
- packages/flat-cache/test/index.test.ts
- packages/flat-cache/tsconfig.json
- packages/flat-cache/vite.config.ts
flat-cache - initial check in of new flat-cache version
> Flat cache  - initial check in of new flat cache version

- packages/cacheable/README.md
- packages/cacheable/package.json
- packages/cacheable/src/memory.ts
cacheable - adding in .items into CacheableMemory
> cacheable - adding in .items into CacheableMemory

- packages/flat-cache/package.json
- packages/flat-cache/src/index.ts
- packages/flat-cache/test/index.test.ts
flat-cache - adding in all and keys method
> flat-cache - adding in all and keys method

- packages/cacheable/README.md
- packages/cacheable/package.json
- packages/cacheable/src/cacheable-item-types.ts
- packages/cacheable/src/index.ts
- packages/cacheable/src/keyv-memory.ts
- packages/cacheable/src/memory.ts
- packages/cacheable/test/index.test.ts
- packages/cacheable/test/keyv-memory.test.ts
- packages/cacheable/test/memory.test.ts
- packages/cacheable/vite.config.ts
- packages/node-cache/README.md
- packages/node-cache/package.json
- packages/node-cache/src/store.ts
Cacheable - adding in get raw, get many raw, set many, get many, and delete many to cacheable memory
> Cacheable - adding in get raw, get many raw, set many, get many, and delete many to cacheable memory 

- packages/cacheable/test/index.test.ts
cacheable - fixing test with sleep not long enough
> cacheable - fixing test with sleep not long enough

- packages/flat-cache/README.md
- packages/flat-cache/src/index.ts
- packages/flat-cache/test/index.test.ts
flat-cache - do not save if there are no changes
> flat-cache - do not save if there are no changes

- packages/flat-cache/README.md
- packages/flat-cache/package.json
- packages/flat-cache/src/index.ts
flat-cache - adding in events via FlatCacheEvents
> flat-cache - adding in events via FlatCacheEvents

- packages/cacheable/src/index.ts
cacheable - expose Keyv enums and types
> cacheable - expose Keyv enums and types

- packages/cacheable/README.md
- packages/cacheable/src/hash.ts
- packages/cacheable/src/index.ts
- packages/cacheable/src/memory.ts
- packages/cacheable/test/hash.test.ts
- packages/cacheable/test/index.test.ts
- packages/cacheable/test/memory.test.ts
cacheable - adding in hash helper function
> cacheable - adding in hash helper function

- packages/node-cache/package.json
- packages/node-cache/src/index.ts
- packages/node-cache/src/store.ts
node-cache - adding in T for casting on get and mget
> node-cache - adding in T for casting on get and mget

- packages/cacheable/README.md
- packages/cacheable/src/index.ts
- packages/cacheable/src/keyv-memory.ts
- packages/cacheable/src/memory.ts
- packages/cacheable/src/wrap.ts
- packages/cacheable/test/index.test.ts
- packages/cacheable/test/memory.test.ts
- packages/cacheable/test/sleep.ts
- packages/cacheable/test/wrap.test.ts
Cacheable - adding in wrap / memoize functionality
> Cacheable - adding in wrap / memoize functionality

- packages/cacheable/package.json
cacheable - version bump to 1.8.0 and @types/node
> cacheable - version bump to 1.8.0 and @types/node

- packages/cache-manager/README.md
- packages/cacheable-request/README.md
- packages/node-cache/README.md
updating npm and licensing badge in readme
> updating npm and licensing badge in readme

- packages/cache-manager/README.md
- packages/cache-manager/package.json
- packages/cache-manager/src/index.ts
- packages/cache-manager/test/example.test.ts
cache-manager - adding examples and updating vitest
> cache-manager - adding examples and updating vitest

- packages/cache-manager/package.json
cache-manager - upgrading typescript and faker-js to latest
> cache-manager - upgrading typescript and faker-js to latest

- packages/cache-manager/package.json
- packages/node-cache/package.json
upgrading keyv to 5.1.0 in cache-manager and node-cache
> upgrading keyv to 5.1.0 in cache-manager and node-cache

- packages/cacheable/README.md
cacheable - updating readme with KeyvCacheableMemory
> cacheable - updating readme with KeyvCacheableMemory

- packages/cacheable/src/hash.ts
- packages/cacheable/src/index.ts
> Cacheable - adding in jsdoc

- packages/cacheable/src/cacheable-item-types.ts
- packages/cacheable/src/index.ts
- packages/cacheable/src/memory.ts
- packages/cacheable/src/stats.ts
> cacheable - updating jsdoc

- packages/cacheable-request/package.json
cacheable-request - upgrading vitest to 2.1.3
> cacheable-request - upgrading vitest to 2.1.3

- packages/cacheable-request/package.json
cacheable-request - upgrading typescript to 5.6.3
> cacheable-request - upgrading typescript to 5.6.3

- packages/cacheable-request/package.json
cacheable-request - upgrading express to 4.21.1
> cacheable-request - upgrading express to 4.21.1

- packages/cacheable-request/package.json
cacheable-request - upgrading rimraf to 6.0.1
> cacheable-request - upgrading rimraf to 6.0.1

- packages/cacheable-request/package.json
cacheable-request - upgrading body-parser to 1.20.3
> cacheable-request - upgrading body-parser to 1.20.3

- packages/flat-cache/package.json
flat-cache - upgrading vitest to 2.1.3
> flat-cache - upgrading vitest to 2.1.3

- packages/flat-cache/package.json
flat-cache - upgrading typescript to 5.6.3
> flat-cache - upgrading typescript to 5.6.3

- packages/flat-cache/package.json
flat-cache - upgrading cacheable and hookified to latest
> flat-cache - upgrading cacheable and hookified to latest

- packages/flat-cache/README.md
- packages/flat-cache/src/index.ts
- packages/flat-cache/test/index.test.ts
flat-cache - serialize and deserialize
> flat-cache - serialize and deserialize

- packages/cache-manager/README.md
- packages/node-cache/README.md
> updating the readme

- packages/node-cache/src/index.ts
- packages/node-cache/test/index.test.ts
> node-cache - updating jsdoc

- packages/cacheable/README.md
- packages/cacheable/package.json
- packages/cacheable/src/index.ts
- packages/cacheable/test/index.test.ts
cacheable - adding in namespace support
> cacheable - adding in namespace support

- packages/cacheable/src/hash-store.ts
- packages/cacheable/src/memory.ts
- packages/cacheable/test/hash-store.test.ts
- packages/cacheable/test/memory.test.ts
cacheable - adding in hash store for memory
> cacheable - adding in hash store for memory

- packages/cacheable/src/memory-lru.ts
- packages/cacheable/src/memory.ts
- packages/cacheable/test/memory-lru.test.ts
cacheable - updating the lru to handle namespace for memory
> cacheable - updating the lru to handle namespace for memory

- packages/cacheable/README.md
- packages/cacheable/src/index.ts
- packages/cacheable/src/memory.ts
- packages/cacheable/src/wrap.ts
- packages/cacheable/test/index.test.ts
- packages/cacheable/test/memory.test.ts
- packages/cacheable/test/wrap.test.ts
cacheable - adding keyPrefix to wrap
> cacheable - adding keyPrefix to wrap

- packages/cache-manager/package.json
cache-manager - upgrading keyv and cacheable to latest
> cache-manager - upgrading keyv and cacheable to latest

- packages/cacheable/package.json
cacheable - upgrading vitest to 2.1.3
> cacheable - upgrading vitest to 2.1.3

- packages/cacheable/package.json
cacheable - upgrading tsup, typescript, and types to latest
> cacheable - upgrading tsup, typescript, and types to latest

- packages/cacheable/package.json
cacheable - upgrading hookified to 1.4.0
> cacheable - upgrading hookified to 1.4.0

- packages/flat-cache/package.json
flat-cache - upgrading tsup to 8.3.5
> flat-cache - upgrading tsup to 8.3.5

- packages/file-entry-cache/package.json
file-entry-cache - upgrading vitest to 2.1.3
> file-entry-cache - upgrading vitest to 2.1.3

- packages/file-entry-cache/package.json
file-entry-cache - upgrading flat-cache to 6.1.1
> file-entry-cache - upgrading flat-cache to 6.1.1

- packages/file-entry-cache/package.json
file-entry-cache - upgrading tsup and typescript to latest
> file-entry-cache - upgrading tsup and typescript to latest

- packages/node-cache/package.json
node-cache - upgrading cacheable to 1.8.1
> node-cache - upgrading cacheable to 1.8.1

- packages/node-cache/package.json
node-cache - upgrading vitest to 2.1.3
> node-cache - upgrading vitest to 2.1.3

- packages/node-cache/package.json
node-cache - upgrading tsup and typescript to latest
> node-cache - upgrading tsup and typescript to latest

- packages/website/package.json
website - upgrading docula to 0.9.4
> website - upgrading docula to 0.9.4

- packages/flat-cache/README.md
flat-cache - updating readme with serialize and deserialize
> flat-cache - updating readme with serialize and deserialize

- packages/cacheable/package.json
- packages/cacheable/src/index.ts
- packages/cacheable/src/memory.ts
- packages/cacheable/src/wrap.ts
- packages/cacheable/test/index.test.ts
- packages/cacheable/test/memory.test.ts
cacheable - fixing keyPrefix bug by making it optional
> cacheable - fixing keyPrefix bug by making it optional

- packages/cacheable/src/index.ts
cacheable - exporting CacheableMemoryOptions
> cacheable - exporting CacheableMemoryOptions

- packages/cache-manager/package.json
- packages/cacheable/package.json
- packages/node-cache/package.json
Cacheable - upgrading keyv to 5.2.1 across all packages
> Cacheable - upgrading keyv to 5.2.1 across all packages

- packages/cacheable-request/package.json
cacheable-request - updating keyv to 5.2.1
> cacheable-request - updating keyv to 5.2.1

- packages/cache-manager/src/index.ts
- packages/cache-manager/test/mset.test.ts
cache-manager - adding in nonBlocking to mset
> cache-manager - adding in nonBlocking to mset

- packages/node-cache/README.md
- packages/node-cache/src/index.ts
- packages/node-cache/test/index.test.ts
node-cache - adding in shorthand handling for ttl
> node-cache - adding in shorthand handling for ttl

- packages/node-cache/README.md
- packages/node-cache/src/store.ts
node-cache - adding in stats option on NodeCacheStore
> node-cache - adding in stats option on NodeCacheStore

- .npmrc
- packages/flat-cache/package.json
flat-cache - upgrading vitest to 2.1.6
> flat-cache - upgrading vitest to 2.1.6

- packages/flat-cache/package.json
flat-cache - upgrading cacheable to 1.8.5
> flat-cache - upgrading cacheable to 1.8.5

- packages/flat-cache/package.json
flat-cache - upgrading flatted to 3.3.2
> flat-cache - upgrading flatted to 3.3.2

- packages/cacheable-request/package.json
cacheable-request - upgrading vitest to 2.1.6
> cacheable-request - upgrading vitest to 2.1.6

- package.json
- vitest.workspace.ts
mono - adding in vitest for workspace support
> mono - adding in vitest for workspace support

- packages/cacheable/README.md
- packages/cacheable/package.json
- packages/cacheable/src/index.ts
- packages/cacheable/src/keyv-memory.ts
- packages/cacheable/test/keyv-memory.test.ts
cacheable - adding in createKeyv and updating memory instance
> cacheable - adding in createKeyv and updating memory instance

- packages/node-cache/README.md
- packages/node-cache/src/index.ts
- packages/node-cache/test/export.test.ts
node-cache - making default export work correctly
> node-cache - making default export work correctly

- packages/cacheable/src/index.ts
cacheable - removing KeyvCacheableMemory as replaced by createKeyv
> cacheable - removing KeyvCacheableMemory as replaced by createKeyv

- packages/cache-manager/package.json
- packages/file-entry-cache/package.json
- packages/flat-cache/package.json
- packages/node-cache/package.json
mono - adding in workspace reference support
> mono - adding in workspace reference support

- packages/cache-manager/README.md
- packages/cache-manager/src/index.ts
- packages/cache-manager/test/ttl.test.ts
cache-manager - adding back in ttl() function to get the expiration
#930 
@Janhouse -- FYI
> cache-manager - adding back in ttl() function to get the expiration

- .npmrc
- packages/cacheable/package.json
- packages/cacheable/src/memory.ts
cacheable - upgrading @keyv/redis to 4.0.2
> cacheable - upgrading @keyv/redis to 4.0.2

- packages/cacheable/src/memory.ts
- packages/cacheable/test/memory.test.ts
- packages/flat-cache/src/index.ts
- packages/flat-cache/test/index.test.ts
flat-cache - loading the expiration from file correctly
#930
> flat-cache - loading the expiration from file correctly

- packages/cacheable/src/memory.ts
cacheable - updating jsDoc for CacheableMemory
> cacheable - updating jsDoc for CacheableMemory

- packages/cacheable/README.md
cacheable - updating readme removing title
> cacheable - updating readme removing title

- packages/cacheable/package.json
cacheable - upgrading xo to 0.60.0
> cacheable - upgrading xo to 0.60.0

- packages/cacheable/package.json
cacheable - upgrading typescript to 5.7.2
> cacheable - upgrading typescript to 5.7.2

- packages/cacheable/package.json
cacheable - upgrading hookified to 1.5.1
> cacheable - upgrading hookified to 1.5.1

- packages/cacheable/package.json
- packages/cacheable/src/coalesce-async.ts
- packages/cacheable/src/memory-lru.ts
- packages/cacheable/src/memory.ts
cacheable - upgrading vitest to 2.1.8
> cacheable - upgrading vitest to 2.1.8

- packages/flat-cache/package.json
flat-cache - upgrading xo to 0.60.0
> flat-cache - upgrading xo to 0.60.0

- packages/flat-cache/package.json
flat-cache - upgrading vitest to 2.1.8
> flat-cache - upgrading vitest to 2.1.8

- CONTRIBUTING.md
- README.md
mono - updating contributing guidelines to address build
> mono - updating contributing guidelines to address build

- packages/cache-manager/package.json
cache-manager - upgrading xo to 0.60.0
> cache-manager - upgrading xo to 0.60.0

- packages/cache-manager/package.json
cache-manager - upgrading vitest to 2.1.8
> cache-manager - upgrading vitest to 2.1.8

- packages/cache-manager/package.json
cache-manager - upgrading faker-js to 9.3.0
> cache-manager - upgrading faker-js to 9.3.0

- packages/cache-manager/package.json
cache-manager - upgrading keyv to 5.2.3
> cache-manager - upgrading keyv to 5.2.3

- packages/cache-manager/package.json
cache-manager - upgrading @keyv/redis to 4.2.0
> cache-manager - upgrading @keyv/redis to 4.2.0

- packages/cacheable/package.json
cacheable - upgrading hookified to 1.6.0
> cacheable - upgrading hookified to 1.6.0

- packages/cacheable/package.json
cacheable - upgrading keyv to 5.2.3
> cacheable - upgrading keyv to 5.2.3

- packages/cacheable-request/package.json
cacheable-request - upgrading xo to 0.60.0
> cacheable-request - upgrading xo to 0.60.0

- packages/cacheable-request/package.json
cacheable-request - upgrading keyv to 5.2.3
> cacheable-request - upgrading keyv to 5.2.3

- packages/cacheable-request/package.json
cacheable-request - upgrading express to 4.21.2
> cacheable-request - upgrading express to 4.21.2

- packages/cacheable-request/package.json
cacheable-request - upgrading vitest to 2.1.8
> cacheable-request - upgrading vitest to 2.1.8

- packages/flat-cache/package.json
flat-cache - upgrading hookified to 1.6.0
> flat-cache - upgrading hookified to 1.6.0

- packages/file-entry-cache/package.json
file-entry-cache - upgrading xo to 0.60.0
> file-entry-cache - upgrading xo to 0.60.0

- packages/node-cache/package.json
node-cache - upgrading xo to 0.60.0
> node-cache - upgrading xo to 0.60.0

- packages/node-cache/package.json
node-cache - upgrading hookified to 1.6.0
> node-cache - upgrading hookified to 1.6.0

- packages/node-cache/package.json
node-cache - upgrading keyv to 5.2.3
> node-cache - upgrading keyv to 5.2.3

- packages/node-cache/package.json
node-cache - upgrading vitest to 2.1.8
> node-cache - upgrading vitest to 2.1.8

- packages/cacheable/src/index.ts
cacheable - fix: when found on secondary use expires to set primary
> cacheable - fix: when found on secondary use expires to set primary

- packages/cache-manager/README.md
- packages/cache-manager/package.json
- packages/cache-manager/src/index.ts
- packages/cache-manager/test/stores.test.ts
cache-manager - feat: adding in stores property
#980
> cache-manager - feat: adding in stores property

- package.json
mono - chore: upgrading vitest and c8 to latest
> mono - chore: upgrading vitest and c8 to latest

- package.json
mono - chore: upgrading wrangler to 3.105.1
> mono - chore: upgrading wrangler to 3.105.1

- packages/cache-manager/package.json
cache-manager - chore: upgrading tsup to 8.3.6
> cache-manager - chore: upgrading tsup to 8.3.6

- packages/cacheable/package.json
cacheable - chore: upgrading tsup to 8.3.6
> cacheable - chore: upgrading tsup to 8.3.6

- packages/cacheable-request/package.json
cacheable-request - chore: upgrading vitest to 3.0.4
> cacheable-request - chore: upgrading vitest to 3.0.4

- packages/cacheable-request/package.json
cacheable-request - chore: upgrading typescript to 5.7.3
> cacheable-request - chore: upgrading typescript to 5.7.3

- packages/file-entry-cache/package.json
file-entry-cache - chore: upgrading vitest to 3.0.4
> file-entry-cache - chore: upgrading vitest to 3.0.4

- packages/file-entry-cache/package.json
file-entry-cache - chore: upgrading typescript and tsup to latest
> file-entry-cache - chore: upgrading typescript and tsup to latest

- packages/flat-cache/package.json
flat-cache - chore: upgrading vitest to 3.0.4
> flat-cache - chore: upgrading vitest to 3.0.4

- packages/flat-cache/package.json
flat-cache - chore: upgrading hookified to 1.7.0
> flat-cache - chore: upgrading hookified to 1.7.0

- packages/flat-cache/package.json
flat-cache - chore: upgrading typescript and tsup to latest
> flat-cache - chore: upgrading typescript and tsup to latest

- packages/node-cache/package.json
node-cache - chore: upgrading vitest to 3.0.4
> node-cache - chore: upgrading vitest to 3.0.4

- packages/node-cache/package.json
node-cache - chore: upgrading typescript and tsup to latest
> node-cache - chore: upgrading typescript and tsup to latest

- packages/cacheable/package.json
- packages/cacheable/test/index.test.ts
- packages/cacheable/test/memory.test.ts
- packages/cacheable/test/wrap.test.ts
adding in nodejs engine requirement
> adding in nodejs engine requirement

- packages/cacheable/package.json
- packages/cacheable/test/memory.test.ts
cacheable - fix: better test for iterator on memory items property
> cacheable - fix: better test for iterator on memory items property

- .github/workflows/codecov.yml
- package.json
- packages/cacheable-request/package.json
- packages/cacheable-request/src/index.ts
mono - chore: upgrading vitest to 3.0.7
> mono - chore: upgrading vitest to 3.0.7

- package.json
mono - chore: upgrading wrangler to 3.111.0
> mono - chore: upgrading wrangler to 3.111.0

- packages/cacheable/package.json
cacheable - chore: upgrading vitest to 3.0.7
> cacheable - chore: upgrading vitest to 3.0.7

- packages/cacheable/package.json
cacheable - chore: upgrading tsup and typescript to lastest
> cacheable - chore: upgrading tsup and typescript to lastest

- packages/cacheable/package.json
cacheable - chore: upgrading faker-js to 9.5.1
> cacheable - chore: upgrading faker-js to 9.5.1

- packages/cacheable/package.json
cacheable - chore: upgrading hookified to 1.7.1
> cacheable - chore: upgrading hookified to 1.7.1

- packages/cacheable/package.json
cacheable - chore: upgrading keyv to 5.3.1
> cacheable - chore: upgrading keyv to 5.3.1

- packages/node-cache/package.json
node-cache - chore: upgrading keyv to 5.3.1
> node-cache - chore: upgrading keyv to 5.3.1

- packages/node-cache/package.json
node-cache - chore: upgrading vitest to 3.0.7
> node-cache - chore: upgrading vitest to 3.0.7

- packages/node-cache/package.json
node-cache - chore: upgrading tsup and typescript to latest
> node-cache - chore: upgrading tsup and typescript to latest

- packages/node-cache/package.json
node-cache - chore: upgrading hookified to 1.7.1
> node-cache - chore: upgrading hookified to 1.7.1

- packages/flat-cache/package.json
flat-cache - chore: upgrading vitest to 3.0.7
> flat-cache - chore: upgrading vitest to 3.0.7

- packages/flat-cache/package.json
flat-cache - chore: upgrading tsup and typescript to lastest
> flat-cache - chore: upgrading tsup and typescript to lastest

- packages/flat-cache/package.json
flat-cache - chore: upgrading hookified to 1.7.1
> flat-cache - chore: upgrading hookified to 1.7.1

- packages/flat-cache/package.json
flat-cache - chore: upgrading flatted to 3.3.3
> flat-cache - chore: upgrading flatted to 3.3.3

- packages/file-entry-cache/package.json
file-entry-cache - chore: upgrading vitest to 3.0.7
> file-entry-cache - chore: upgrading vitest to 3.0.7

- packages/cache-manager/package.json
cache-manager - chore: upgrading vitest to 3.0.7
> cache-manager - chore: upgrading vitest to 3.0.7

- packages/cache-manager/package.json
cache-manager - chore: upgrading keyv to 5.3.1
> cache-manager - chore: upgrading keyv to 5.3.1

- packages/cache-manager/package.json
cache-manager - chore: upgrading typescript and tsup to latest
> cache-manager - chore: upgrading typescript and tsup to latest

- packages/cacheable-request/package.json
cacheable-request - chore: upgrading vitest to 3.0.7
> cacheable-request - chore: upgrading vitest to 3.0.7

- packages/cacheable-request/package.json
cacheable-request - chore: upgrading keyv to 5.3.1
> cacheable-request - chore: upgrading keyv to 5.3.1

- packages/cacheable-request/package.json
cacheable-request - chore: upgrading typescript and tsup to latest
> cacheable-request - chore: upgrading typescript and tsup to latest

- packages/cache-manager/README.md
cache-manager - feat: adding in v5 to v6 documentation
> cache-manager - feat: adding in v5 to v6 documentation

- package.json
mono - chore: adding in approve builds for pnpm
> mono - chore: adding in approve builds for pnpm

- package.json
mono - chore: upgrading vitest to 3.1.1
> mono - chore: upgrading vitest to 3.1.1

- packages/benchmark/package.json
benchmark - chore: upgrading tsx to 4.19.3
> benchmark - chore: upgrading tsx to 4.19.3

- packages/benchmark/package.json
benchmark - chore: upgrading fakerjs to 9.6.0
> benchmark - chore: upgrading fakerjs to 9.6.0

- packages/benchmark/package.json
benchmark - chore: upgrading tinybench to 4.0.1
> benchmark - chore: upgrading tinybench to 4.0.1

- packages/cache-manager/package.json
cache-manager - chore: upgrading keyv to 5.3.2
> cache-manager - chore: upgrading keyv to 5.3.2

- packages/cacheable/package.json
cacheable - chore: upgrading cacheable to 3.0.7
> cacheable - chore: upgrading cacheable to 3.0.7

- packages/cacheable/package.json
cacheable - chore: upgrading lru-cache to 11.1.0
> cacheable - chore: upgrading lru-cache to 11.1.0

- packages/cacheable/package.json
cacheable - chore: upgrading keyv to 5.3.2
> cacheable - chore: upgrading keyv to 5.3.2

- packages/cacheable/package.json
cacheable - chore: upgrading hookified to 1.8.1
> cacheable - chore: upgrading hookified to 1.8.1

- packages/cacheable/package.json
cacheable - chore: upgrading fakerjs to 9.6.0
> cacheable - chore: upgrading fakerjs to 9.6.0

- packages/cacheable-request/package.json
cacheable-request - chore: upgrading vitest to 3.1.1
> cacheable-request - chore: upgrading vitest to 3.1.1

- packages/cacheable-request/package.json
cacheable-request - chore: upgrading keyv to 5.3.2
> cacheable-request - chore: upgrading keyv to 5.3.2

- packages/cacheable-request/package.json
cacheable-request - chore: upgrading body-parser to 2.2.0
> cacheable-request - chore: upgrading body-parser to 2.2.0

- packages/flat-cache/package.json
flat-cache - chore: upgrading vitest to 3.1.1
> flat-cache - chore: upgrading vitest to 3.1.1

- packages/flat-cache/package.json
flat-cache - chore: upgrading hookified to 1.8.1
> flat-cache - chore: upgrading hookified to 1.8.1

- packages/node-cache/package.json
node-cache - chore: upgrading vitest to 3.1.1
> node-cache - chore: upgrading vitest to 3.1.1

- packages/node-cache/package.json
node-cache - chore: upgrading keyv to 5.3.2
> node-cache - chore: upgrading keyv to 5.3.2

- packages/website/package.json
website - chore: upgrading tsx to 4.19.3
> website - chore: upgrading tsx to 4.19.3

- packages/website/package.json
website - chore: upgrading docula to 0.11.0
> website - chore: upgrading docula to 0.11.0

- packages/website/package.json
website - chore: upgrading fs-extra to 11.3.0
> website - chore: upgrading fs-extra to 11.3.0

- packages/cacheable/README.md
cacheable - feat: adding in the BEFORE_SECONDARY_SETS_PRIMARY
> cacheable - feat: adding in the BEFORE_SECONDARY_SETS_PRIMARY

- packages/cache-manager/package.json
- packages/cache-manager/src/index.ts
- packages/cache-manager/test/mdel.test.ts
- packages/cache-manager/test/mset.test.ts
Fixed bug when mset, mdel in blocking mode were actually non blocking
**What kind of change does this PR introduce?** Bug fix
> Fix blocking mdel, mset

- packages/cache-manager/README.md
cache-manager - fix: fixing legacy storage adapter readme
#1088
> cache-manager - fix: fixing legacy storage adapter readme

- packages/benchmark/package.json
benchmark - chore: upgrading tinybench components to latest
> benchmark - chore: upgrading tinybench components to latest

- packages/benchmark/package.json
benchmark - chore: upgrading quick-lru to 7.0.1
> benchmark - chore: upgrading quick-lru to 7.0.1

- packages/cache-manager/package.json
cache-manager - chore: upgrading vitest to 3.1.3
> cache-manager - chore: upgrading vitest to 3.1.3

- packages/cache-manager/package.json
cache-manager - chore: upgrading typescript to 5.8.3
> cache-manager - chore: upgrading typescript to 5.8.3

- packages/cache-manager/package.json
cache-manager - chore: upgrading @faker-js/faker to 9.7.0
> cache-manager - chore: upgrading @faker-js/faker to 9.7.0

- packages/cache-manager/package.json
- packages/cache-manager/test/wrap.test.ts
cache-manager - chore: upgrading keyv to 5.3.3
> cache-manager - chore: upgrading keyv to 5.3.3

- packages/cacheable/package.json
cacheable - chore: upgrading vitest to 3.1.3
> cacheable - chore: upgrading vitest to 3.1.3

- packages/cacheable/package.json
cacheable - chore: upgrading typescript to 5.8.3
> cacheable - chore: upgrading typescript to 5.8.3

- packages/cacheable/package.json
cacheable - chore: upgrading @faker-js/faker to 9.7.0
> cacheable - chore: upgrading @faker-js/faker to 9.7.0

- packages/cache-manager/test/wrap.test.ts
- packages/cacheable/package.json
cacheable - chore: upgrading hookified to 1.8.2
> cacheable - chore: upgrading hookified to 1.8.2

- packages/cacheable/package.json
cacheable - chore: upgrading keyv to 5.3.3
> cacheable - chore: upgrading keyv to 5.3.3

- packages/cacheable-request/package.json
cacheable-request - chore: upgrading vitest to 3.1.3
> cacheable-request - chore: upgrading vitest to 3.1.3

- packages/cacheable-request/package.json
cacheable-request - chore: upgrading typescript to 5.8.3
> cacheable-request - chore: upgrading typescript to 5.8.3

- packages/cacheable-request/package.json
cacheable-request - chore: upgrading keyv to 5.3.3
> cacheable-request - chore: upgrading keyv to 5.3.3

- packages/node-cache/package.json
node-cache - chore: upgrading hookified to 1.8.2
> node-cache - chore: upgrading hookified to 1.8.2

- packages/node-cache/package.json
node-cache - chore: upgrading typescript to 5.8.3
> node-cache - chore: upgrading typescript to 5.8.3

- packages/node-cache/package.json
node-cache - chore: upgrading vitest to 3.1.3
> node-cache - chore: upgrading vitest to 3.1.3

- packages/flat-cache/package.json
flat-cache - chore: upgrading vitest to 3.1.3
> flat-cache - chore: upgrading vitest to 3.1.3

- packages/flat-cache/package.json
flat-cache - chore: upgrading hookified to 1.8.2
> flat-cache - chore: upgrading hookified to 1.8.2

- .github/workflows/codecov.yml
- .github/workflows/deploy-website.yml
- .github/workflows/tests.yml
mono - fix: adding in permissions on github actions
> mono - fix: adding in permissions on github actions

- packages/website/package.json
website - chore: upgrading docula to 0.11.1
> website - chore: upgrading docula to 0.11.1

- packages/cache-manager/README.md
**What kind of change does this PR introduce?** 
- Fixes comment in README TTL code example in cache-manager package
> Fix comment in ttl example code of cache-manager package

- packages/cacheable-request/package.json
cacheable-request - chore: upgrading tsup to 8.5.0
> cacheable-request - chore: upgrading tsup to 8.5.0

- packages/cacheable-request/package.json
cacheable-request - chore: upgrading http-cache-semantics to 4.2.0
> cacheable-request - chore: upgrading http-cache-semantics to 4.2.0

- packages/cacheable-request/package.json
cacheable-request - chore: upgrading @keyv/sqlite to 4.0.4
> cacheable-request - chore: upgrading @keyv/sqlite to 4.0.4

- packages/node-cache/package.json
- packages/node-cache/src/index.ts
node-cache - chore: upgrading xo to 1.1.0
> node-cache - chore: upgrading xo to 1.1.0

- packages/node-cache/package.json
node-cache - chore: upgrading tsup to 8.5.0
> node-cache - chore: upgrading tsup to 8.5.0

- packages/node-cache/package.json
node-cache - chore: upgrading hookified to 1.9.1
> node-cache - chore: upgrading hookified to 1.9.1

- packages/node-cache/package.json
node-cache - chore: upgrading vitest to 3.2.2
> node-cache - chore: upgrading vitest to 3.2.2

- packages/website/package.json
website - chore: upgrading docula to 0.12.2
> website - chore: upgrading docula to 0.12.2

- packages/flat-cache/package.json
- packages/flat-cache/src/index.ts
- packages/flat-cache/test/index.test.ts
flat-cache - chore: upgrading xo to 1.1.0
> flat-cache - chore: upgrading xo to 1.1.0

- packages/flat-cache/package.json
flat-cache - chore: upgrading vitest to 3.2.2
> flat-cache - chore: upgrading vitest to 3.2.2

- packages/flat-cache/package.json
flat-cache - chore: upgrading hookified to 1.9.1
> flat-cache - chore: upgrading hookified to 1.9.1

- packages/cache-manager/src/index.ts
- packages/cacheable/src/index.ts
- packages/cacheable/test/secondary-primary.test.ts
cache-manager - fix: get events were not exposed as a type
https://github.com/jaredwray/cacheable/issues/1158
> cache-manager - fix: get events were not exposed as a type

- packages/cacheable/README.md
- packages/cacheable/src/wrap.ts
- packages/cacheable/test/wrap.test.ts
cacheable -  feat: adding createKey to wrap functions
> cacheable -  feat: adding createKey to wrap functions

- packages/flat-cache/README.md
- packages/flat-cache/src/index.ts
- packages/flat-cache/test/index.test.ts
flat-cache - feat: adding in loadFileStream with progress
> flat-cache - feat: adding in loadFileStream with progress

- packages/node-cache/README.md
- packages/node-cache/src/store.ts
node-cache - updating readme for NodeCacheStore
> node-cache - updating readme for NodeCacheStore

- packages/benchmark/node-cache.ts
- packages/benchmark/package.json
- packages/cacheable/package.json
- packages/node-cache/README.md
- packages/node-cache/package.json
node-cache - fix: fixing documentation with API and async
> node-cache - fix: fixing documentation with API and async

- packages/cache-manager/README.md
- packages/cache-manager/package.json
cache-manager - chore: upgrading vitest to 3.2.4
> cache-manager - chore: upgrading vitest to 3.2.4

- packages/cacheable-request/package.json
cacheable-request - chore: upgrading vitest to 3.2.4
> cacheable-request - chore: upgrading vitest to 3.2.4

- packages/cacheable-request/package.json
cacheable-request - chore: upgrading keyv to 5.3.4
> cacheable-request - chore: upgrading keyv to 5.3.4

- packages/cacheable-request/package.json
cacheable-request - chore: upgrading normalize-url to 8.0.2
> cacheable-request - chore: upgrading normalize-url to 8.0.2

- packages/cacheable-request/vitest.config.ts
- packages/website/package.json
website - chore: upgrading docula to 0.13.0
> website - chore: upgrading docula to 0.13.0

- packages/cacheable/package.json
cacheable - chore: upgrading vitest to 3.2.4
> cacheable - chore: upgrading vitest to 3.2.4

- packages/cacheable/package.json
cacheable - chore: upgrading tsup to 8.5.0
> cacheable - chore: upgrading tsup to 8.5.0

- packages/cacheable/package.json
cacheable - chore: upgrading keyv to 5.3.4
> cacheable - chore: upgrading keyv to 5.3.4

- packages/node-cache/README.md
- packages/node-cache/src/index.ts
node-cache - feat: adding in clear documentation on useClones
> node-cache - feat: adding in clear documentation on useClones

- packages/file-entry-cache/package.json
file-entry-cache - chore: upgrading xo to 1.1.1
> file-entry-cache - chore: upgrading xo to 1.1.1

- .github/workflows/codecov.yml
- .github/workflows/deploy-website.yml
- .github/workflows/tests.yml
mono - chore: removing approve builds
> mono - chore: removing approve builds

- packages/website/package.json
website - chore: upgrading @types/node to latest
> website - chore: upgrading @types/node to latest

- packages/cache-manager/package.json
cache-manager - chore: upgrading xo to 1.2.0
> cache-manager - chore: upgrading xo to 1.2.0

- packages/cache-manager/package.json
cache-manager - chore: upgrading @keyv/redis to 4.6.0
> cache-manager - chore: upgrading @keyv/redis to 4.6.0

- packages/node-cache/package.json
node-cache - chore: upgrading xo to 1.2.1
> node-cache - chore: upgrading xo to 1.2.1

- packages/node-cache/package.json
node-cache - chore: upgrading keyv to 5.4.0
> node-cache - chore: upgrading keyv to 5.4.0

- packages/flat-cache/package.json
flat-cache - chore: upgrading xo to 1.2.1
> flat-cache - chore: upgrading xo to 1.2.1

- packages/flat-cache/README.md
- packages/flat-cache/package.json
- packages/flat-cache/src/index.ts
- packages/flat-cache/test/index.test.ts
flat-cache - fix: updating documentation on clearCacheById
flat-cache - fix: updating documentation on clearCacheById
> flat-cache - fix: updating documentation on clearCacheById

- packages/utils/package.json
utils - fix: updating package to the correct keywords
> utils - fix: updating package to the correct keywords

- packages/utils/README.md
- packages/utils/src/cacheable-item-types.ts
- packages/utils/src/shorthand-time.ts
utils - feat: adding in readme
> utils - feat: adding in readme

- packages/utils/README.md
- packages/utils/src/hash.ts
- packages/utils/test/hash.test.ts
utils - feat: making hashToNumber universal
> utils - feat: making hashToNumber universal

- packages/memoize/README.md
memoize - fix: fixing the readme npmjs
> memoize - fix: fixing the readme npmjs

- packages/cacheable-request/test/cache.test.ts
cacheable-request - feat: adding testTimeout to some unit tests
> cacheable-request - feat: adding testTimeout to some unit tests

- package.json
mono - chore: upgrading wrangler to 4.28.0
> mono - chore: upgrading wrangler to 4.28.0

- packages/website/package.json
website - chore: upgrading fs-extra to 11.3.1
> website - chore: upgrading fs-extra to 11.3.1

- packages/website/package.json
website - chore: upgrading docula to 0.13.1
> website - chore: upgrading docula to 0.13.1

- packages/cacheable-request/package.json
cacheable-request - chore: upgrading typescript to 5.9.2
> cacheable-request - chore: upgrading typescript to 5.9.2

- packages/cache-manager/package.json
cache-manager - chore: upgrading typescript to 5.9.2
> cache-manager - chore: upgrading typescript to 5.9.2

- packages/node-cache/package.json
node-cache - fix: adding in supported node versions
https://github.com/e18e/ecosystem-issues/issues/188#issuecomment-3167457502
> node-cache - fix: adding in supported node versions

- packages/node-cache/package.json
node-cache - chore: upgrading hookified to 1.11.0
> node-cache - chore: upgrading hookified to 1.11.0

- packages/flat-cache/package.json
flat-cache - chore: upgrading typescript to 5.9.2
> flat-cache - chore: upgrading typescript to 5.9.2

- packages/file-entry-cache/package.json
file-entry-cache - chore: upgrading typescript to 5.9.2
> file-entry-cache - chore: upgrading typescript to 5.9.2

- packages/benchmark/biome.json
- packages/benchmark/package.json
- packages/cache-manager/biome.json
- packages/cache-manager/package.json
- packages/cacheable-request/biome.json
- packages/cacheable-request/package.json
- packages/cacheable/biome.json
- packages/cacheable/package.json
- packages/file-entry-cache/biome.json
- packages/file-entry-cache/package.json
- packages/flat-cache/biome.json
- packages/flat-cache/package.json
- packages/memoize/biome.json
- packages/memoize/package.json
- packages/memory/biome.json
- packages/memory/package.json
- packages/net/biome.json
- packages/net/package.json
- packages/node-cache/biome.json
- packages/node-cache/package.json
- packages/utils/biome.json
- packages/utils/package.json
mono - fix: updating biome to fail on warnings
> mono - fix: updating biome to fail on warnings

- packages/utils/package.json
utils - chore: upgrading keyv adapters to latest
> utils - chore: upgrading keyv adapters to latest

- packages/utils/package.json
utils - chore: upgrading @fakerjs/faker to 10.0.0
> utils - chore: upgrading @fakerjs/faker to 10.0.0

- packages/memoize/package.json
memoize - chore: upgrading @biomejs/biome to 2.2.2
> memoize - chore: upgrading @biomejs/biome to 2.2.2

- packages/net/package.json
net - chore: upgrading hookified to 1.12.0
> net - chore: upgrading hookified to 1.12.0

- packages/net/package.json
net - chore: upgrading @biomejs/biome to 2.2.2
> net - chore: upgrading @biomejs/biome to 2.2.2

- packages/net/package.json
net - chore: upgrading @faker-js/faker to 10.0.0
> net - chore: upgrading @faker-js/faker to 10.0.0

- packages/memory/package.json
memory - chore: upgrading typescript to 5.9.2
> memory - chore: upgrading typescript to 5.9.2

- packages/memory/package.json
memory - chore: upgrading @biomejs/biome to 2.2.2
> memory - chore: upgrading @biomejs/biome to 2.2.2

- packages/cacheable/src/index.ts
- packages/cacheable/test/index.test.ts
cacheable - fix: handling nonBlocking errors better
> cacheable - fix: handling nonBlocking errors better

- package.json
mono - chore: upgrading wrangler to latest
> mono - chore: upgrading wrangler to latest

- packages/cache-manager/package.json
cache-manager - chore: upgrading @keyv/redis to 5.1.1
> cache-manager - chore: upgrading @keyv/redis to 5.1.1

- packages/cacheable-request/package.json
cacheable-request - chore: upgrading @biomejs/biome to 2.2.3
> cacheable-request - chore: upgrading @biomejs/biome to 2.2.3

- packages/website/package.json
website - chore: upgrading docula to 0.20.0
> website - chore: upgrading docula to 0.20.0

- packages/utils/README.md
- packages/utils/src/index.ts
- packages/utils/src/is-object.ts
- packages/utils/src/less-than.ts
- packages/utils/src/lt.ts
- packages/utils/src/run-if-fn.ts
- packages/utils/test/is-object.test.ts
- packages/utils/test/less-than.test.ts
- packages/utils/test/run-if-fn.test.ts
utils - feat: adding in helper functions from cache manager
> utils - feat: adding in helper functions from cache manager

- packages/cacheable/src/index.ts
- packages/cacheable/test/index.test.ts
- packages/node-cache/package.json
- packages/node-cache/src/store.ts
- packages/node-cache/test/store.test.ts
cacheable - feat: moving to Keyv native setMany
> cacheable - feat: moving to Keyv native setMany

- packages/cacheable/src/index.ts
- packages/cacheable/test/index.test.ts
cacheable - feat: moving to native Keyv deleteMany
> cacheable - feat: moving to native Keyv deleteMany

- packages/cacheable/src/index.ts
- packages/cacheable/test/index.test.ts
cacheable - feat: moving to native Keyv getRaw
> cacheable - feat: moving to native Keyv getRaw

- packages/cacheable/package.json
cacheable - chore: upgrading lru-cache to 11.2.1
> cacheable - chore: upgrading lru-cache to 11.2.1

- packages/cacheable/package.json
cacheable - chore: upgrading hookified to 1.12.0
> cacheable - chore: upgrading hookified to 1.12.0

- packages/cacheable/package.json
cacheable - chore: upgrading biome and faker-js to latest
> cacheable - chore: upgrading biome and faker-js to latest

- packages/node-cache/package.json
node-cache - chore: upgrading keyv to 5.5.1
> node-cache - chore: upgrading keyv to 5.5.1

- packages/file-entry-cache/package.json
file-entry-cache - chore: upgrading biome to 2.2.4
> file-entry-cache - chore: upgrading biome to 2.2.4

- packages/utils/package.json
utils - chore: upgrading biome to 2.2.4
> utils - chore: upgrading biome to 2.2.4

- packages/utils/package.json
utils - chore: upgrading @keyv/redis to 5.1.2
> utils - chore: upgrading @keyv/redis to 5.1.2

- packages/memoize/package.json
memoize - fix: removing lru-cache as no longer needed
> memoize - fix: removing lru-cache as no longer needed

- packages/memoize/package.json
memoize - chore: upgrading biome to 2.2.4
> memoize - chore: upgrading biome to 2.2.4

- packages/cache-manager/package.json
- packages/cacheable-request/package.json
- packages/cacheable/package.json
- packages/memory/package.json
- packages/node-cache/package.json
mono - chore upgrading keyv to 5.5.3
> mono - chore upgrading keyv to 5.5.3

- packages/net/package.json
net - chore: upgrading undici to 7.16.0
> net - chore: upgrading undici to 7.16.0

- packages/net/package.json
net - chore: upgrading hookified to 1.12.1
> net - chore: upgrading hookified to 1.12.1

- packages/net/package.json
net - chore: upgrading biome to 2.2.4
> net - chore: upgrading biome to 2.2.4

- packages/net/src/index.ts
net - feat: moving to FetchOptions in Net
> net - feat: moving to FetchOptions in Net

- packages/net/README.md
net - feat: adding readme information for fetch helpers
> net - feat: adding readme information for fetch helpers

- packages/net/README.md
- packages/net/src/index.ts
- packages/net/test/index.test.ts
net - feat: adding in put method helper
> net - feat: adding in put method helper

- packages/net/src/fetch.ts
- packages/net/test/fetch.test.ts
net - feat: if there is no cache passed then it does not cache
> net - feat: if there is no cache passed then it does not cache

- packages/net/src/index.ts
- packages/net/test/index.test.ts
net - feat: ability to set the caching to false on get()
> net - feat: ability to set the caching to false on get()

- packages/net/README.md
- packages/net/src/index.ts
- packages/net/test/index.test.ts
net - feat: ability for put to have caching if true
> net - feat: ability for put to have caching if true

- packages/net/README.md
- packages/net/src/index.ts
- packages/net/test/index.test.ts
net - feat: patch with caching when set to true
> net - feat: patch with caching when set to true

- packages/net/README.md
- packages/net/src/index.ts
- packages/net/test/index.test.ts
net - feat: added caching to delete as an option
> net - feat: added caching to delete as an option

- packages/net/README.md
- packages/net/src/fetch.ts
- packages/net/src/index.ts
- packages/net/test/fetch.test.ts
- packages/net/test/index.test.ts
net - feat: renaming useHttpCache to httpCachePolicy
> net - feat: renaming useHttpCache to httpCachePolicy

- packages/file-entry-cache/README.md
- packages/file-entry-cache/src/index.ts
- packages/file-entry-cache/test/cwd.test.ts
- packages/file-entry-cache/test/file-rename.test.ts
- packages/file-entry-cache/test/path-sanitization.test.ts
file-entry-cache - feat: adding in current working directory
> file-entry-cache - feat: adding in current working directory

- packages/cacheable/src/index.ts
- packages/utils/package.json
- packages/utils/src/index.ts
- packages/utils/src/is-keyv-instance.ts
cacheable - fix: moving isKeyvInstance to utils
> cacheable - fix: moving isKeyvInstance to utils

- packages/utils/src/is-keyv-instance.ts
- packages/utils/test/is-keyv-instance.test.ts
utils - fix: adding in keyv instance
> utils - fix: adding in keyv instance

- packages/cache-manager/package.json
cache-manager - chore: upgrading typescript to 5.9.3
> cache-manager - chore: upgrading typescript to 5.9.3

- packages/cache-manager/package.json
cache-manager - chore: upgrading @keyv/redis to 5.1.2
> cache-manager - chore: upgrading @keyv/redis to 5.1.2

- packages/cacheable-request/package.json
cacheable-request - chore: upgrading normalize-url to 8.1.0
> cacheable-request - chore: upgrading normalize-url to 8.1.0

- packages/website/package.json
website - chore - upgrading tsx to 4.20.6
> website - chore - upgrading tsx to 4.20.6

- packages/website/package.json
- packages/website/src/docs.ts
- packages/website/tsconfig.json
website - chore: migrating from fs-extra to node:fs
> website - chore: migrating from fs-extra to node:fs

- packages/net/src/index.ts
net - fix: adding in FetchRequestInit
> net - fix: adding in FetchRequestInit

- .gitignore
- packages/file-entry-cache/README.md
- packages/file-entry-cache/package.json
- packages/file-entry-cache/src/index.ts
- packages/file-entry-cache/test/index.test.ts
file-entry-cache - feat: adding in logging capabilities
> file-entry-cache - feat: adding in logging capabilities
