lib/caching.js
lib/multi_caching.js
lib/stores/memory.js
test/caching.unit.js
test/multi_caching.unit.js
test/stores/options.unit.js

Add the ability to pass in options.  These options can then be used by the stores.
Our use case is using Riak as a distributed fault tolerant cache.
We want to pass in if quorum is required for writes, read or deletes.
A get request would look like:
```
cache.get('ActiveLock', function(err, val){}, {quorum: true});
```
Also there is a test case fixed in ef044b8  The timeout parameter was on the wrong closing curly brace.

Add Additional Options Parameter

---

lib/stores/memory.js

The length option is particularly useful with lru-cache if you want to store large objects of varying size and limit memory usage.
https://github.com/isaacs/node-lru-cache#options

Pass dispose, length & stale options to lru-cache

---

examples/redis_example/redis_store.js
lib/caching.js
test/caching.unit.js

Potential issue was instroduced on https://github.com/BryanDonovan/node-cache-manager/commit/f3809c8b762b38e8ce0a22155b528e419b5602fc using Redis stores and wrap.
This was done following the bug report https://github.com/BryanDonovan/node-cache-manager/issues/25 I'm sorry I was not able to confirm the fix so I made this PR
Using Redis, null is returned from cache when data does not exists
In other stores, null can still be stored and undefined used when data does not exist
The issue occurs only when calling wrap in simple cache, not multi cache so I guess multi cache do not use isCacheableValue
This PR includes:
- Each store can implement its own custom method
- Tests to keep coverage to 100%
- Updated redis cache exemple with the override since redis can return null when data does not …

Stores can override isCacheableValue

---

lib/multi_caching.js
test/multi_caching.unit.js

Hopeful fix for https://github.com/BryanDonovan/node-cache-manager/issues/28
CC @diversario, @danagle
You can test this by putting this in your package.json:
```json
"node-cache-manager": "git+ssh://git@github.com:BryanDonovan/node-cache-manager.git#feature/fix-domain-errors"
```

trying to fix #28 by checking if callbackFiller has key in domain.error

---

README.md

i've created a store engine for storing the cached values into the filesystem, availiable already in npm (cache-manager-fs) - this pull request adds the store engine to the README.md

added file system store engine to README.md

---

.jshintrc
lib/caching.js
lib/callback_filler.js
lib/multi_caching.js
lib/stores/memory.js
package.json
test/caching.unit.js
test/multi_caching.unit.js
test/run.js

To handle #24 
There is the promise support WIP branch to make the cache manager handle promises.
I have some issues on the existing cache providers, and for tests. Right now only wrap (simple cache and multi cache) and get/set (multi cache) are implemented.
The issue with single store cache is that cache-manager is directly binded to the underlying methods, and to add promise support in get I need to change the method usage and add a breaking change, that I would like to avoid.
Some more tests to be added (100% on wrap, drop to 97% on get/set ATM)

Promise support

---

lib/caching.js
lib/callback_filler.js
lib/multi_caching.js
test/caching.unit.js
test/multi_caching.unit.js

Removes `domain` error handling (see #38).

removing domain error catching from caching/multi-caching

---

lib/caching.js
test/caching.unit.js

Just noticed that callback in `wrap` method never gets triggered second time if a non cacheable value is returned. This pull request fixes it.

Triggering callback in wrap after it was queued

---

README.md

I've added my store for hazelcast (https://github.com/marudor/node-cache-manager-hazelcast) to the README.

Add hazelcast store to readme

---

README.md

I note that `node-cache-manager` already has a memory store by default in my repo.

Add node-cache-manager-memory-store link to readme

---

README.md

Added simple redis-store to `README.md`. This store is directly built upon `node_redis`, without using the `sol-redis-pool` package.

Add node-cache-manager-redis-store link to readme

---

README.md

Added link to the `cache-manager-ioredis` store to README.md. This store is directly built upon `ioredis`.

Add node-cache-manager-ioredis link to readme

---

.gitignore
README.md
lib/caching.js
lib/multi_caching.js
lib/stores/memory.js
lib/utils.js
package.json
test/caching.unit.js
test/multi_caching.unit.js
test/utils.unit.js

Hello!
This PR is to allow setting, getting and deleting multiple keys at once. It works both on the caching and the multicaching. As such, the "wrap" method now accepts an unlimited number of keys.
I am aware that this is a big feature with loads of changes. I had to do some refactoring to stay under the cyclomatic complexity. Let me know all your comments.
This feature does not add any breaking change to node-cache-manager.
I opened a PR in "node-cache-manager-redis-store" to give support to this feature in redis store (https://github.com/dabroek/node-cache-manager-redis-store/pull/6)

feature: allow setting, getting and deleting  multiple keys

---

lib/multi_caching.js

The "keysToFetch" in getFromHighestProrityCache() was not being emptied causing the fetch to go through all the caches even though the result had been found.

fix(multi_caching): getFromHighestProrityCache()

---

lib/caching.js
test/caching.unit.js

Using `cache-manager-memcached-store` store's `isCacheableValue` method will fail because when caching assigns the value to `self._isCacheableValue` it does not pass the `this` context.
This PR takes care that store's context is passed to `isCacheableValue`.

Don't brake store's this context for isCacheableValue method

---

Makefile
README.md
lib/caching.js
test/caching.unit.js

Hi there 👋This is a small change that allows compilers like [`@zeit/ncc`](https://github.com/zeit/ncc) to properly work with `cache-manager`. 🙂
This fix [would allow us](https://github.com/imjohnbo/cache-manager-zeit-ncc/blob/8f69d40275240079d9acd31de846095640e91f1f/package.json) to use `ncc` to compile [`probot`](https://github.com/probot/probot), a downstream user of `cache-manager`. The tracking issue for this compilation error is [here](https://github.com/zeit/ncc/issues/480).
Thanks for taking a look! 🙏

Add .js to module path to fix compilers

---

README.md
lib/stores/memory.js
test/stores/memory.unit.js

This is to allow the user to choose whether the memory store clones values before storing them in cache (via the `set` method).  Related issues:
- https://github.com/BryanDonovan/node-cache-manager/issues/100
- https://github.com/BryanDonovan/node-cache-manager/pull/103
- https://github.com/BryanDonovan/node-cache-manager/issues/132
- https://github.com/BryanDonovan/node-cache-manager/issues/134
I'm trying to decide if this change warrants a major version bump.  It makes sense to do a major bump in the sense that anyone using version 2.10.1 or earlier could run into issues with 2.10.2, 2.11.0, or 2.11.1, and the new version.  So maybe a clean break is good.  On the other hand, the new changes work the same as 2.11.1, so in that sense it's a minor bump.

adding way to disable cloning of values in memory store

---

lib/stores/memory.js

As requsted by #122, updateAgeOnGet can now be set as a args attribute when calling cacheManager.caching(). Default is false, as is in  [lru-cache](https://github.com/isaacs/node-lru-cache/blob/master/index.js).

Added the updateAgeOnGet option

---

README.md
lib/caching.js
lib/multi_caching.js
test/caching.unit.js
test/multi_caching.unit.js

Fixes: #93 
This PR implements a mechanism to update the cached value in background by adding a new "refreshThreshold" configuration parameter for cache stores.
If `refreshThreshold` is set and if the `ttl(key)` method is available in the used store, after retrieving a value from cache the TTL of that entry will be checked.
If the remaining TTL is less than `refreshThreshold`, the system will spawn a background worker to update the value, following same rules as standard fetching. In case of multicaching, the value will be then updated in all the stores. In the meantime, the system will return the old value until expiration (or update).
In case of multicaching, the store that will be checked for refresh is the one where the key will be found first (highest priority).
NOTES:
* Background …

Background refresh of expiring entries

---

lib/caching.js
lib/multi_caching.js
test/caching.unit.js
test/multi_caching.unit.js

This is a followup to #138 (a feature is not a feature if it has no bugs... )
* fix: option object passthrough and TTL calculation in multi-caching
* fix: Remove item from background queue if entry is not expired
* optimization: avoid running checks if refreshThreshold is not set (avoids some useless function calls)

Background refresh fixes

---

lib/multi_caching.js

Some error of underlying store, like memcached-plus, throw exception that is not capture and could propagate to main loop.
CF assertKey for exemple: https://github.com/victorquinn/memcache-plus/blob/master/lib/client.js#L16-L22.
Surround by try catch to capture and restore the error to the chain promise / callback.

Catch uncaught exception to pass it to callback

---

README.md

I suggest to remove [node-cache-manager-fs](https://github.com/hotelde/node-cache-manager-fs) from the list of Store Engines of `README.md` because the lib is not working as expected.
After spending too much time checking my code, I tried another lib and it everything worked as expected.
I found out the lib has already a consequent number of issue related to the problem:
- https://github.com/hotelde/node-cache-manager-fs/issues/23
- https://github.com/hotelde/node-cache-manager-fs/issues/15
- https://github.com/hotelde/node-cache-manager-fs/issues/5
- https://github.com/hotelde/node-cache-manager-fs/issues/2
I recommend to use [node-cache-manager-fs-hash](https://github.com/rolandstarke/node-cache-manager-fs-hash) instead.

Remove node-cache-manager-fs from README.md

---

lib/stores/memory.js
test/stores/memory.unit.js

PR for issue [How to use dump and load API since built-in memory cache is node-lru-cach](https://github.com/BryanDonovan/node-cache-manager/issues/169)
Add dump and load methods for memory store

feat: add dump and load methods for memory store

---

lib/stores/memory.js
package-lock.json
package.json

- updated 3.2.3 (had to remove package-lock.json and rebuild due to ENOTFOUND (reason: getaddrinfo ENOTFOUND npm.apple.com)
- fixed lint failure in lib/stores/memory.js
- ran make, all passed
I've also noticed that running npm install -d, has increased the package-lock.json to v2 lockfile instead of v1.
If needs be I can regenerate a v1 lockfile, let me know!
https://github.com/caolan/async/blob/master/CHANGELOG.md#v322
https://nvd.nist.gov/vuln/detail/CVE-2021-43138
Thanks, 
Matt

Fix for potential prototype polution exploit in async < 3.2.2

---

lib/stores/memory.js

Hi, I upgraded to cache-manager@4.0.0 and TTL was not working.
Perhaps it was an omission in #193 updates.
* In lru-cache@7.x, `maxAge` was renamed to `ttl`.
* The `set()` function takes options objects instead of ttl integer.
See: https://github.com/isaacs/node-lru-cache/blob/main/CHANGELOG.md#specific-api-changes
cache-manager: 4.0.0
lru-cache: 7.10.1
node: 18.2.0
npm: 8.9.0

fix: ttl not working

---

lib/stores/memory.js
test/stores/memory.unit.js

Added support for TTL seconds as the third argument in set() function of memory store strategy.
According to types from @types/cache-manager this function should support TTL in third arg but it can't. So this PR is fix this issue.
[Link to set() type definition](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/9b425ba3f0507dd34b52cfa39772b40975fc41ef/types/cache-manager/index.d.ts#L64``)

feat: added support for ttl as the third arg in set function of memory store

---

CHANGELOG.md
README.md

Minor changes in docs :
- CHANGELOG.md : 
- Add `ttl` unit change on 5.0.0 changes
- Add dates for versions from 4.0.0 to 5.0.1
- README.md : 
- Change `miliseconds` => `milliseconds`

Docs : Add ttl unit change in CHANGELOG and fix typo in README

---

README.md
src/multi-caching.ts
test/multi-caching.test.ts

Fix for #361. (clone of #366 but with a clean commit)
The implementation is similar to the functionality that existed in previous versions and is missing in v5. However, mset takes the same array-style arguments as the single-store version in v5 (as opposed to the pre-v5-style with key, value pair argument list).

feat: add mget(), mset(), mdel() to multiCache

---

src/stores/memory.ts

type MemoryConfig in memoryStore is incorrect and could cause some confusion (it did for me a bit)
this is the type in node-lru-cache package
[https://github.com/isaacs/node-lru-cache/blob/main/src/index.ts#L219](https://github.com/isaacs/node-lru-cache/blob/main/src/index.ts#L219)
as you can see value is first annd key is second.

sizeCalculation key,value swap

---

src/stores/memory.ts
test/caching.test.ts
test/multi-caching.test.ts
test/stores/memory.test.ts

added tests for sizeCalculation (regarding [this](https://github.com/node-cache-manager/node-cache-manager/pull/480#issuecomment-1567218560))
changed out faker deprecated methods with the recommended replacements
added lru-cache's calculatedSize to memoryStore example and wrote a test for it

test(memory store): sizeCalculation

---

.github/workflows/test.yml
package.json

updating to always run vitest with coverage

updating to always run vitest with coverage

---

README.md
src/caching.ts

**What kind of change does this PR introduce?** (Bug fix)
In stores like redis, if no `ttl` value is set, `store.ttl(key)` returns `-1`. This causes an issue with the `refreshThreshold` feature, where the comparison mentioned below will always lead to running the function
https://github.com/node-cache-manager/node-cache-manager/blob/2eca5a0c6c905fe706ed9eaca9152dedd512ef7e/src/caching.ts#L92
I've added an additional check to check for `-1` value, and not run the function again.
Note: Wasn't sure where to add test for this, please let me know if I need to. I have tested this manually with my work project

fix(refreshThreshold): don't run if ttl is -1

---

package.json
src/caching.ts
test/caching.test.ts

Fixes #417
In the `v4.x` version, the `caching.wrap()` function would coalesce multiple concurrent requests to minimize how many times the generator function was invoked. This was a helpful optimization to reduce load on downstream systems like databases and APIs.
This pull request adds that cache miss relief logic back by using the [promise-coalesce](https://github.com/douglascayers/promise-coalesce) module, which is said logic in a generic, reusable function.
For tests, the `#417` issue test demonstrates the undesired behavior. The updated `wrap()` tests demonstrate the desired behavior by coalescing requests.
Thanks

fix(caching): coalesce concurrent requests to `wrap` function

---

package.json

adding in prepare for the build

adding in prepare for the build

---

package.json

Sourcemap files are ignored when publishing because source paths are specified in them. For example, v8 module will search for the source code path according to the sourcemap when executing the coverage command in the typescript environment. If it is not found, an error will be reported.
Just publishing the compiled js and d.ts files is enough.
like [this](https://github.com/midwayjs/midway/actions/runs/7170370531/job/19522952358?pr=3492).
related: https://github.com/midwayjs/midway/pull/3492
@jaredwray

fix: exclude sourcemap when package publish

---

package.json

updating clean to scripts

---

.github/workflows/test.yml
README.md
src/caching.ts
test/caching.test.ts

Add non-async `createCache()` that `caching()` uses to set up methods (keep current functionality intact).
Having `createCache()` as addition to `caching()` allows devs to create cache instances synchronously, and i.e use as default params in methods:
```ts
/** Awesome service that will use memory store as default cache, if nothing else specified */ 
class MyItemService {
constructor(public cache = createCache(memoryStore())) { }
}
```

feat: support sync cache creation

---

src/caching.ts
test/caching.test.ts

Bug fix for https://github.com/node-cache-manager/node-cache-manager/issues/619

619: Ensure that background refresh only calls fn once.

---

README.md
src/caching.ts
src/multi-caching.ts
test/caching.test.ts
test/multi-caching.test.ts

Add refreshThreshold as parameter of wrap function. Fix #606

---

README.md
src/caching.ts
test/caching.test.ts
test/utils.ts

This PR introduces `onBackgroundRefreshError` configuration option, which makes it possible to handle promise rejections originating from background refreshes.
As it stands now, depending on your Node version, process might crash. `process.on('uncaughtException', ...)` fixes that, but we missed a bit more... targeted approach to handling these errors, so here is a PR.

Ability to catch promise rejections from background refreshes

---

README.md

updating readme to show configuration options

updating readme to show configuration options

---

README.md

updating readme with correct settings on shouldCloneBeforeSet

updating readme with correct settings on shouldCloneBeforeSet

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/test.yml
README.md
package.json

moving templates and repo paths to cache-manager

moving templates and repo paths to cache-manager

---

packages/cache-manager-redis-yet/package.json

redis-yet - upgrading vitest to 1.5.2

redis-yet - upgrading vitest to 1.5.2

---

packages/cache-manager/README.md
packages/cache-manager/src/caching.ts
packages/cache-manager/src/multi-caching.ts
packages/cache-manager/test/caching.test.ts
packages/cache-manager/test/multi-caching.test.ts

When using `caching.on` and `multicaching.on`, there's no way to:
* Know the circumstances that caused the error (key, data, operation, etc...)
* Unsubscribe from the emitter
Introducing this changes, consumers can better monitor and classify errors.

feat: add details to error event 

---

packages/cache-manager-redis-yet/src/index.ts

- [x ] Followed the [Contributing](https://github.com/node-cache-manager/cache-manager/blob/main/CONTRIBUTING.md) guidelines.
Includes new configuration option for create cache's keys prefix if this option is informed. If this new configuration option didn't setup nothing happens.

feat: cache s key prefix configuration

---

packages/cache-manager-ioredis-yet/package.json

ioredis - upgrading vitest to 1.6.0

ioredis - upgrading vitest to 1.6.0

---

packages/cache-manager/README.md

**What kind of change does this PR introduce?** Docs update
Im new to this library and was scratching my head for a good hour as to why the middleware example wasnt working, then i discovered the TTL was incorrectly configured, this PR makes a minor adjustment to fix that.

Fix express example having a 10ms instead of 10 second cache ttl

---

packages/cache-manager/README.md
packages/cache-manager/src/caching.ts
packages/cache-manager/src/multi-caching.ts
packages/cache-manager/src/utils.ts
packages/cache-manager/test/caching.test.ts
packages/cache-manager/test/multi-caching.test.ts
packages/cache-manager/test/utils.test.ts

Introducing non-blocking set for wrap operations. 
In V4 when the wrap operation was called, results were returned before backfilling the cache(s).
This changed in V5 and cache(s) are backfilled before returning results, leading to slower throughput. 
This PR adds the option to restore the behaviour of V4.

non-blocking set for wrap function

---

packages/cache-manager/package.json

cache-manager - fix moving back to lru-cache version ^10.2.2

cache-manager - fix moving back to lru-cache version ^10.2.2

---

packages/cacheable/src/index.ts

cacheable - adding multiple stores

cacheable - adding multiple stores

---

packages/node-cache/README.md
packages/node-cache/src/index.ts
packages/node-cache/test/index.test.ts

node-cache - updating readme with API

node-cache - updating readme with API

---

packages/cache-manager/package.json
packages/node-cache/package.json

node-cache - upgrading typescript to 5.6.2

node-cache - upgrading typescript to 5.6.2

---

packages/node-cache/README.md
packages/node-cache/src/store.ts
packages/node-cache/test/store.test.ts

node-cache - adding setTtl() to NodeCacheStore

node-cache - adding setTtl() to NodeCacheStore

---

packages/cache-manager/README.md

cache-manager - updating readme with wrap on nonBlocking

cache-manager - updating readme with wrap on nonBlocking

---

packages/cache-manager/package.json
packages/cacheable-request/package.json
packages/cacheable/package.json
packages/cacheable/src/index.ts
packages/cacheable/test/index.test.ts
packages/cacheable/test/keyv-memory.test.ts
packages/file-entry-cache/package.json
packages/flat-cache/package.json
packages/node-cache/package.json

The field has been supported, see <https://docs.npmjs.com/cli/v10/configuring-npm/package-json#repository>.
Adding the field will make the `npm repo` command more useful. E.g.
With the field:
```sh-session
$ npm repo vitest --no-browser
vitest repo available at the following URL:
https://github.com/vitest-dev/vitest/tree/HEAD/packages/vitest
```
Without the field:
```sh-session
$ npm repo cacheable --no-browser
cacheable repo available at the following URL:
https://github.com/jaredwray/cacheable
```
feature

Add `repository.directory` field to each packages' `package.json`

---

packages/cacheable/README.md
packages/cacheable/src/memory.ts
packages/cacheable/test/memory.test.ts

cacheable - adding hasMany to CacheableMemory

cacheable - adding hasMany to CacheableMemory

---

packages/cacheable/README.md
packages/cacheable/src/index.ts
packages/cacheable/src/memory.ts
packages/cacheable/src/wrap.ts
packages/cacheable/test/index.test.ts
packages/cacheable/test/memory.test.ts
packages/cacheable/test/wrap.test.ts

Cacheable - fixing the wrap function to use the key as a prefix fir #861 
@edwdch - thanks and it was a mistake as the key is the prefix and is now required.

Cacheable - fixing the wrap function to use the key as a prefix

---

CONTRIBUTING.md
packages/cache-manager/package.json

cache-manager - upgrading tsup, faker, and types to latest

cache-manager - upgrading tsup, faker, and types to latest

---

packages/file-entry-cache/src/index.ts
packages/file-entry-cache/test/index.test.ts

file-entry-cache - fix recreating cache from a file

---

packages/cacheable/README.md
packages/cacheable/package.json
packages/cacheable/src/coalesce-async.ts
packages/cacheable/src/wrap.ts
packages/cacheable/test/wrap.test.ts

cacheable - adding in stampede protection via coalesce async

cacheable - adding in stampede protection via coalesce async

---

packages/file-entry-cache/package.json

file-entry-cache - upgrading flat-cache to 6.1.2

file-entry-cache - upgrading flat-cache to 6.1.2

---

packages/file-entry-cache/package.json

file-entry-cache - upgrading vitest to 2.1.4

file-entry-cache - upgrading vitest to 2.1.4

---

packages/cache-manager/README.md
packages/cache-manager/src/index.ts
packages/cache-manager/src/keyv-adapter.ts
packages/cache-manager/test/disconnect.test.ts
packages/cache-manager/test/keyv-adapter.test.ts

Adds the ability to disconnect from the relevant stores inside the cache

cache-manager - adding disconnect to cache

---

packages/file-entry-cache/package.json

file-entry-cache - upgrading vitest to 2.1.5

file-entry-cache - upgrading vitest to 2.1.5

---

packages/file-entry-cache/src/index.ts
packages/file-entry-cache/test/index.test.ts

file-entry-cache - fixing bug on save meta.data and changed state #901

file-entry-cache - fixing bug on save meta.data and changed state

---

packages/file-entry-cache/package.json
packages/file-entry-cache/src/index.ts
packages/file-entry-cache/test/index.test.ts

file-entry-cache - changed does not get set on meta.data changes

file-entry-cache - changed does not get set on meta.data changes

---

packages/node-cache/package.json
packages/node-cache/src/index.ts
packages/node-cache/src/store.ts

node-cache - moving to hookified instead of eventemitter3

node-cache - moving to hookified instead of eventemitter3

---

packages/cache-manager/README.md
packages/cache-manager/src/index.ts
packages/cache-manager/test/wrap.test.ts

Feature & docs update. Closes #916

feat(cache-manager): add refreshAllStores option (close #916)

---

packages/cacheable/src/memory.ts

When a check interval is passed to the cache, cachable starts an interval that prevents node from exiting unless it gets cleared. There is a public method to stop the interval, but it's flagged as internal use only.
Given this, I've opted to unref the interval to allow the node process to exit cleanly.
The other alternative would be to add a public close/disconnect API method -- the Keyv interface seems to account for this case -- however, it does make the API more cumbersome for the end-user.

cacheable - unref check interval to allow node exit

---

packages/cacheable/README.md

```diff
import { Keyv } from 'keyv';
import { KeyvCacheableMemory } from 'cacheable';
const keyv = new Keyv({ store: new KeyvCacheableMemory() });
await keyv.set('foo', 'bar');
-const value = await keyv.get('key);
+const value = await keyv.get('foo);
console.log(value); // bar 
```

fix typo in code example in readme file

---

packages/cache-manager/src/index.ts

Solves #923 
This PR introduces a named return type, `Cache`, for the `createCache()` method. This type explicitly defines the structure of the cache instance, enabling:
Improved type inference and autocomplete in TypeScript.
Easier integration with frameworks like NestJS by allowing direct reference to the `Cache` type.
Stronger type guarantees, ensuring compatibility with future updates.
**Does this PR introduce a breaking change?**
No. The changes are fully backward compatible. The new type definition is an explicit representation of the existing inferred type, so no runtime behavior is affected.
**Code example**
```typescript
import { Cache, …
```

cache-manager - add named return type to createCache

---

packages/flat-cache/README.md

The function is called `clearCacheById()`
https://github.com/jaredwray/cacheable/blob/8ea2b079cdec11c6f068fb8a116e8561f42fa1c5/packages/flat-cache/src/index.ts#L462
documentation correction
- N/A Tests for the changes have been added (for bug fixes/features) with 100% code coverage.
- N/A Docs have been added / updated (for bug fixes / features)

Fix error in docs

---

.github/workflows/codecov.yml
packages/cache-manager/package.json
packages/cacheable-request/package.json
packages/cacheable/package.json
packages/file-entry-cache/package.json
packages/flat-cache/package.json
packages/node-cache/package.json

mono - moving to prepublish instead of prepare

mono - moving to prepublish instead of prepare

---

packages/cache-manager/test/wrap.test.ts
packages/cacheable/test/index.test.ts
packages/flat-cache/src/index.ts

flat-cache - removing console.log remnant

flat-cache - removing console.log remnant

---

packages/cacheable/src/index.ts
packages/cacheable/src/memory.ts

Preserve args type when wrapping

preserve args type when wrapping

---

packages/file-entry-cache/package.json

file-entry-cache - upgrading vitest to 2.1.8

file-entry-cache - upgrading vitest to 2.1.8

---

packages/cacheable/src/index.ts

cacheable - feat: adding in jsDoc on CacheableOptions

cacheable - feat: adding in jsDoc on CacheableOptions

---

packages/cache-manager/src/index.ts
packages/cache-manager/test/wrap.test.ts

`wrap` function: re-evaluate ttl function on fresh value when triggered by `refreshThreshold`. rather then use ttl evaluated for cached value.

on wrap with refreshThreshold - re-evaluate ttl function

---

packages/cache-manager/README.md
packages/cache-manager/src/index.ts
packages/cache-manager/test/cache-id.test.ts
packages/cache-manager/test/wrap.test.ts

`wrap` function: nested `wrap` call on other cache instance with same key - results in deadlock, where `wrap` function call hangs indefinitely

bugfix wrap function: nested wrap call on other cache instance - results in deadlock

---

packages/cache-manager/README.md
packages/cache-manager/src/index.ts
packages/cache-manager/test/wrap.test.ts

cache-manager: `wrap()` method - support `refreshThreshold` argument as number or Function  of `(value:T) => number`. Similar to how `ttl` is supported.
`refreshThreshold` is ideally defined in proportion to `ttl` - which is supported also as a Function.
One popular use case for example: caching jwt tokens - cache `ttl` should be set according to returned jwt expiration. Likewise, `refreshThreshold` needs to be set proportionally. Especially when different clients change their jwt token lifetime dynamically.

cache-manager: wrap() method - support refreshThreshold argument as Function

---

packages/cache-manager/README.md
packages/cache-manager/src/index.ts
packages/cache-manager/src/is-object.ts
packages/cache-manager/test/wrap.test.ts

cache-manager: wrap() method:
-  add support for an options object parameter instead of the separate `ttl` and `refreshThreshold` params.
- additionally a new parameter is added to the options object, that will change the method's return value to raw stored data including expiration timestamp.
Closes https://github.com/jaredwray/cacheable/issues/997

cache-manager:wrap() method - support options parameter and raw return data

---

packages/cache-manager/test/wrap.test.ts
packages/flat-cache/README.md

- [ YES] Docs have been added / updated (for bug fixes / features)
Fix: wrong (v5) example in getting started for load.

flat-cache -  fix: wrong (v5) example in getting started for load.

---

packages/cacheable/src/index.ts
packages/cacheable/test/index.test.ts

TTLs are not propagated when utilizing multiple cacheable instances with a shared secondary store.
This PR starts with adding test cases that define the expected behavior of TTL propagation. For the added cases, we use two cacheable instances that utilize a shared secondary store, writing to the first and then reading from the second. It helps to consider the use-case where we have two processes using the same Redis database as the secondary store.
Test case status: 7/7 passing.

TTL Propagation Bug Fixes

---

packages/file-entry-cache/package.json

file-entry-cache - chore: upgrading vitest to 3.1.1

file-entry-cache - chore: upgrading vitest to 3.1.1

---

packages/cacheable/src/memory.ts

**Please check if the PR fulfils these requirements**
This PR introduces a bug fix and a small improvement.
The bug fix is related to the _hashCache variable not having its key deleted when it's deleted from the store. This would result in increasing memory consumption over time.
A use case: you receive a lot of IDs (1000s / second) and you want to cache them for a short period of time (using TTL). They are deleted from the store, but not from the hashCache, thus increasing the memory consumption indefinitely.
I could also add this change under an opt-in flag if the current behaviour is intended (e.g. if a key is deleted, but later you check it again and you don't want to compute the hash again). This …

cacheable - fix: deleting a key should delete entry from hash cache

---

packages/cacheable/README.md
packages/cacheable/src/index.ts
packages/cacheable/test/index.test.ts

Proposal from the #1116 issue
**What kind of change does this PR introduce?** 
This pull request introduces a new "raw" mode for the `get` and `getMany` methods in the `Cacheable` library, allowing users to retrieve full metadata for cache entries instead of just the stored values. The changes include updates to the library's implementation, documentation, and tests.
* Added support for a `raw` option in the `get` and `getMany` methods, enabling retrieval of full metadata (`StoredDataRaw<T>`) for cache entries. This includes updates to method signatures, logic for handling primary and secondary stores, and the return structure. (`packages/cacheable/src/index.ts`, [[1]](diffhunk://#diff-e787642663183987ec0514d540e867e94325aeee022004cfe2 …

cacheable - feat: Expose raw option on get / getMany to surface TTL/expiration

---

packages/file-entry-cache/README.md
packages/file-entry-cache/src/index.ts
packages/file-entry-cache/test/index.test.ts

file-entry-cache - feat: adding in useModifiedTime option
#1047 and #914

file-entry-cache - feat: adding in useModifiedTime option

---

packages/cacheable/README.md
packages/cacheable/src/index.ts
packages/cacheable/src/wrap.ts
packages/cacheable/test/index.test.ts
packages/cacheable/test/wrap.test.ts

This pull request introduces a new `getOrSet` method to the `Cacheable` class, refactors the `wrap` function to leverage this new method, and adds corresponding tests to ensure functionality. The changes aim to improve cache management by simplifying code and preventing cache stampedes.
* Added a `getOrSet` method to the `Cacheable` class, which retrieves a cached value or computes and caches it if not present. This method includes support for TTL and error caching. (`packages/cacheable/src/index.ts`)
* Refactored the `wrap` function to delegate caching logic to the new `getOrSet` method, simplifying the implementation. …

feat: getOrSet

---

packages/node-cache/src/index.ts
packages/node-cache/test/index.test.ts

node-cache - fix: returning T instead of any

node-cache - fix: returning T instead of any

---

packages/file-entry-cache/package.json

file-entry-cache - chore: upgrading vitest to 3.2.4

file-entry-cache - chore: upgrading vitest to 3.2.4

---

packages/cache-manager/src/index.ts
packages/cache-manager/test/events.test.ts
packages/cache-manager/test/multiple-stores.test.ts

Implements [#1128](https://github.com/jaredwray/cacheable/issues/1128) by adding **store layer identification** to event payloads in `cache-manager`.  
Previously, event payloads (`get`, `set`, etc.) did not include which store/layer (primary or secondary) was responsible. This limited monitoring and debugging when multiple stores were configured.
- Added `_storeLabel` helper:
- `"primary"` for index `0`
- `"secondary:N"` for deeper layers
- Updated `get` and `set` (including errors) to emit the `store` field in event payloads.
- Added unit tests:
- **events.test.ts** – verifies `get` payload includes store and value, error events include store.
- …

cache-manager - feat: add store layer identification to event payloads

---

packages/net/src/fetch.ts
packages/net/src/index.ts
packages/net/test/fetch.test.ts
packages/net/test/index.test.ts

net - feat: adding in get helper for fetch

net - feat: adding in get helper for fetch

---

packages/net/src/fetch.ts
packages/net/src/index.ts
packages/net/test/fetch.test.ts
packages/net/test/index.test.ts

net - feat: adding in post from fetch

net - feat: adding in post from fetch

---

packages/net/src/fetch.ts
packages/net/src/index.ts
packages/net/test/fetch.test.ts
packages/net/test/index.test.ts

net - feat: adding in head helper method for fetch

net - feat: adding in head helper method for fetch

---

packages/cacheable/src/index.ts
packages/cacheable/test/index.test.ts

cacheable - feat: moving to @cacheable/utils hash function

cacheable - feat: moving to @cacheable/utils hash function

---

packages/net/src/index.ts

net - feat: adding in jsDoc for cache property

net - feat: adding in jsDoc for cache property

---

packages/file-entry-cache/src/index.ts
packages/file-entry-cache/test/index.test.ts
packages/file-entry-cache/test/relative-eslint.test.ts

file-entry-cache - fix: removing useModifiedTime as not needed

file-entry-cache - fix: removing useModifiedTime as not needed

---

packages/file-entry-cache/package.json

file-entry-cache - chore: upgrading biome to 2.2.5

file-entry-cache - chore: upgrading biome to 2.2.5
